#!/usr/bin/env python
import sys
import csv
from pathlib import Path
from datetime import datetime

if len(sys.argv) != 2:
    print("Usage: update.py timetable.csv")
    sys.exit(1)

file = sys.argv[1]
updateFile = Path("./Update.sql")

with open(file, mode="r") as f:
    reader = csv.reader(f)
    next(reader)
    data = ["\t".join(row) for row in reader]


with open(updateFile, mode="w+") as f:
    f.write(f"""-- This file was generated by update.py on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
DELETE FROM public.timetable;

COPY public.timetable (day, period_name, start_time, end_time, location, course_code, section) FROM stdin;
""")
    f.write("\n".join(data))

print(f"Update file generated at {updateFile}")
