-- This file was generated by update.py on 2024-10-10 13:45:59
DELETE FROM public.timetable;

COPY public.timetable (day, period_name, start_time, end_time, location, course_code, section) FROM stdin;
Tuesday	Lecture	13:15	14:45	Radichel MPR	BUSA 432 - Organisational Development	Section A
Thursday	Lecture	13:15	14:45	Radichel MPR	BUSA 432 - Organisational Development	Section A
Friday	Discussion	08:00	09:00	Radichel MPR	BUSA 432 - Organisational Development	Section A
Monday	Lecture	09:45	11:15	Apt Hall 217	BUSA210 - Financial Accounting	Section B
Wednesday	Lecture	09:45	11:15	Apt Hall 217	BUSA210 - Financial Accounting	Section B
Friday	Discussion	12:15	13:15	Radichel MPR	BUSA210 - Financial Accounting	Section B
Monday	Lecture	11:30	13:00	Norton-Motulsky 207B	BUSA210 - Financial Accounting	Section C
Wednesday	Lecture	11:30	13:00	Norton-Motulsky 207B	BUSA210 - Financial Accounting	Section C
Friday	Discussion	13:55	14:55	Radichel MPR	BUSA210 - Financial Accounting	Section C
Monday	Lecture	08:00	09:30	Apt Hall 217	BUSA210 - Financial Accounting	Section A
Wednesday	Lecture	08:00	09:30	Apt Hall 217	BUSA210 - Financial Accounting	Section A
Friday	Discussion	10:20	11:20	Radichel MPR	BUSA210 - Financial Accounting	Section A
Monday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA224 - Finance for Non-finance Managers	Section B
Wednesday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA224 - Finance for Non-finance Managers	Section B
Friday	Discussion	09:10	10:10	Norton-Motulsky 207B	BUSA224 - Finance for Non-finance Managers	Section B
Monday	Lecture	11:30	13:00	Nutor Hall 216	BUSA224 - Finance for Non-finance Managers	Section C
Wednesday	Lecture	11:30	13:00	Nutor Hall 216	BUSA224 - Finance for Non-finance Managers	Section C
Thursday	Discussion	16:45	17:45	D-Lab 102	BUSA224 - Finance for Non-finance Managers	Section C
Monday	Lecture	08:00	09:30	Norton-Motulsky 207B	BUSA224 - Finance for Non-finance Managers	Section A
Wednesday	Lecture	08:00	09:30	Norton-Motulsky 207B	BUSA224 - Finance for Non-finance Managers	Section A
Friday	Discussion	08:00	09:00	Norton-Motulsky 207B	BUSA224 - Finance for Non-finance Managers	Section A
Tuesday	Lecture	09:45	11:15	Nutor Hall 216	BUSA304 - Operations Management	Section B
Thursday	Lecture	09:45	11:15	Nutor Hall 216	BUSA304 - Operations Management	Section B
Friday	Discussion	09:10	10:10	Nutor Hall 216	BUSA304 - Operations Management	Section B
Tuesday	Lecture	11:30	13:00	Norton-Motulsky 207B	BUSA304 - Operations Management	Section C
Thursday	Lecture	11:30	13:00	Norton-Motulsky 207B	BUSA304 - Operations Management	Section C
Friday	Discussion	13:55	14:55	Nutor Hall 216	BUSA304 - Operations Management	Section C
Tuesday	Lecture	08:00	09:30	Nutor Hall 216	BUSA304 - Operations Management	Section A
Thursday	Lecture	08:00	09:30	Nutor Hall 216	BUSA304 - Operations Management	Section A
Friday	Discussion	08:00	09:00	Nutor Hall 216	BUSA304 - Operations Management	Section A
Monday	Lecture	09:45	11:15	Nutor Hall 216	BUSA323 - Corporate Finance	Section B
Wednesday	Lecture	09:45	11:15	Nutor Hall 216	BUSA323 - Corporate Finance	Section B
Friday	Discussion	12:15	13:15	Nutor Hall 216	BUSA323 - Corporate Finance	Section B
Monday	Lecture	08:00	09:30	Nutor Hall 115	BUSA323 - Corporate Finance	Section A
Wednesday	Lecture	08:00	09:30	Nutor Hall 115	BUSA323 - Corporate Finance	Section A
Friday	Discussion	10:20	11:20	Jackson Hall 115	BUSA323 - Corporate Finance	Section A
Tuesday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA341 - Marketing	Section B
Wednesday	Discussion	15:00	16:00	Databank Foundation Hall 218	BUSA341 - Marketing	Section B
Thursday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA341 - Marketing	Section B
Tuesday	Lecture	08:00	09:30	Norton-Motulsky 207B	BUSA341 - Marketing	Section A
Wednesday	Discussion	13:45	14:45	Databank Foundation Hall 218	BUSA341 - Marketing	Section A
Thursday	Lecture	08:00	09:30	Norton-Motulsky 207B	BUSA341 - Marketing	Section A
Monday	Lecture	09:45	11:15	Radichel MPR	BUSA350 - International Trade and Policy	Section B
Wednesday	Lecture	09:45	11:15	Radichel MPR	BUSA350 - International Trade and Policy	Section B
Friday	Discussion	12:15	13:15	Norton-Motulsky 207B	BUSA350 - International Trade and Policy	Section B
Monday	Lecture	11:30	13:00	Radichel MPR	BUSA350 - International Trade and Policy	Section C
Wednesday	Lecture	11:30	13:00	Radichel MPR	BUSA350 - International Trade and Policy	Section C
Friday	Discussion	13:55	14:55	Norton-Motulsky 207B	BUSA350 - International Trade and Policy	Section C
Monday	Lecture	08:00	09:30	Radichel MPR	BUSA350 - International Trade and Policy	Section A
Wednesday	Lecture	08:00	09:30	Radichel MPR	BUSA350 - International Trade and Policy	Section A
Friday	Discussion	10:20	11:20	Norton-Motulsky 207B	BUSA350 - International Trade and Policy	Section A
Monday	Discussion	11:30	13:00	Nutor Hall 115	BUSA401_A - Entrepreneurship I	Section A
Wednesday	Lecture	11:30	14:45	Nutor Hall 115	BUSA401_A - Entrepreneurship I	Section A
Tuesday	Lecture	09:45	11:15	Nutor Hall 115	BUSA402 - Business Law	Section B
Thursday	Lecture	09:45	11:15	Nutor Hall 115	BUSA402 - Business Law	Section B
Friday	Discussion	12:15	13:15	Nutor Hall 100	BUSA402 - Business Law	Section B
Tuesday	Lecture	08:00	09:30	Nutor Hall 115	BUSA402 - Business Law	Section A
Thursday	Lecture	08:00	09:30	Nutor Hall 115	BUSA402 - Business Law	Section A
Friday	Discussion	10:20	11:20	Nutor Hall 100	BUSA402 - Business Law	Section A
Monday	Seminar	13:15	14:45	Jackson Hall 116	BUSA411 - Applied Project I (BA)	Section A
Wednesday	Seminar	13:15	14:45	Jackson Hall 116	BUSA411 - Applied Project I (BA)	Section A
Monday	Lecture	09:45	11:15	Nutor Hall 115	BUSA422 - Corporate Finance	Section B
Wednesday	Lecture	09:45	11:15	Nutor Hall 115	BUSA422 - Corporate Finance	Section B
Friday	Discussion	12:15	13:15	Nutor Hall 115	BUSA422 - Corporate Finance	Section B
Monday	Lecture	08:00	09:30	Nutor Hall 216	BUSA422 - Corporate Finance	Section A
Wednesday	Lecture	08:00	09:30	Nutor Hall 216	BUSA422 - Corporate Finance	Section A
Friday	Discussion	10:20	11:20	Nutor Hall 216	BUSA422 - Corporate Finance	Section A
Monday	Lecture	15:00	16:30	Norton-Motulsky 207B	BUSA423 - International Finance	Section A
Wednesday	Lecture	15:00	16:30	Norton-Motulsky 207B	BUSA423 - International Finance	Section A
Friday	Discussion	13:55	14:55	Nutor Hall 100	BUSA423 - International Finance	Section A
Tuesday	Lecture	15:00	16:30	Databank Foundation Hall 218	BUSA431 - Real Estate Development	Section A
Thursday	Lecture	15:00	16:30	Databank Foundation Hall 218	BUSA431 - Real Estate Development	Section A
Friday	Discussion	09:10	10:10	Databank Foundation Hall 218	BUSA431 - Real Estate Development	Section A
Monday	Lecture	16:45	19:15	Radichel MPR	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Tuesday	Lecture	16:45	19:15	Radichel MPR	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Wednesday	Lecture	16:45	19:15	Radichel MPR	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Thursday	Lecture	16:45	19:15	Radichel MPR	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Friday	Discussion	09:10	10:10	Radichel MPR	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Monday	Lecture	15:00	16:30	Jackson Hall 116	BUSA442 - Strategic Brand Management	Section A
Wednesday	Lecture	15:00	16:30	Jackson Hall 116	BUSA442 - Strategic Brand Management	Section A
Friday	Discussion	13:55	14:55	Nutor Hall 115	BUSA442 - Strategic Brand Management	Section A
Tuesday	Lecture	13:15	14:45	Nutor Hall 216	BUSA444 - Supply Chain Management	Section A
Thursday	Lecture	13:15	14:45	Nutor Hall 216	BUSA444 - Supply Chain Management	Section A
Friday	Discussion	08:00	09:00	Jackson Hall 116	BUSA444 - Supply Chain Management	Section A
Monday	Seminar	13:15	14:45	Nutor Hall 216	BUSA491 - Undergraduate Thesis I (BA)	Section A
Wednesday	Seminar	13:15	14:45	Nutor Hall 216	BUSA491 - Undergraduate Thesis I (BA)	Section A
Monday	Lab	10:30	12:30	Fab Lab 203	CE451 - Embedded Systems	Section A
Tuesday	Lecture	08:00	09:30	Fab Lab 203	CE451 - Embedded Systems	Section A
Thursday	Lecture	08:00	09:30	Fab Lab 203	CE451 - Embedded Systems	Section A
Tuesday	Lecture	11:30	13:00	Fab Lab 203	CS 452 - Machine Learning	Section A
Wednesday	Lab	11:30	13:00	Fab Lab 203	CS 452 - Machine Learning	Section A
Thursday	Lecture	11:30	13:00	Fab Lab 203	CS 452 - Machine Learning	Section A
Tuesday	Lecture	08:00	09:30	Jackson Lab 221	CS212 - Computer Programming for CS	Section A
Wednesday	Discussion	08:00	09:30	Jackson Lab 222	CS212 - Computer Programming for CS	Section A
Thursday	Lecture	08:00	09:30	Jackson Lab 221	CS212 - Computer Programming for CS	Section A
Tuesday	Lecture	08:00	09:30	Apt Hall 217	CS213 - Object-Oriented Programming	Section A
Thursday	Lecture	08:00	09:30	Apt Hall 217	CS213 - Object-Oriented Programming	Section A
Friday	Lab	10:20	11:50	Apt Hall 217	CS213 - Object-Oriented Programming	Section A
Tuesday	Lecture	09:45	11:15	Apt Hall 217	CS213 - Object-Oriented Programming	Section B
Thursday	Lecture	09:45	11:15	Apt Hall 217	CS213 - Object-Oriented Programming	Section B
Friday	Lab	12:15	13:45	Apt Hall 217	CS213 - Object-Oriented Programming	Section B
Tuesday	Lecture	11:30	13:00	Apt Hall 217	CS213 - Object-Oriented Programming	Section C
Thursday	Lecture	11:30	13:00	Apt Hall 217	CS213 - Object-Oriented Programming	Section C
Friday	Lab	13:55	15:25	Apt Hall 217	CS213 - Object-Oriented Programming	Section C
Monday	Lecture	08:00	09:30	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section A
Wednesday	Lecture	08:00	09:30	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section A
Friday	Lab	10:20	11:50	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section A
Monday	Lecture	09:45	11:15	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section B
Wednesday	Lecture	09:45	11:15	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section B
Friday	Lab	12:15	13:45	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section B
Monday	Lecture	11:30	13:00	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section C
Wednesday	Lecture	11:30	13:00	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section C
Friday	Lab	13:55	15:25	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section C
Monday	Lecture	13:15	14:45	Jackson Hall 115	CS313 - Intermediate Computer Programming	Section A
Tuesday	Lecture	13:15	14:45	Jackson Hall 115	CS313 - Intermediate Computer Programming	Section A
Thursday	Lab	13:15	14:45	Jackson Hall 115	CS313 - Intermediate Computer Programming	Section A
Monday	Lecture	15:00	16:30	Jackson Hall 115	CS313 - Intermediate Computer Programming	Section B
Tuesday	Lecture	15:00	16:30	Jackson Hall 115	CS313 - Intermediate Computer Programming	Section B
Thursday	Lab	15:00	16:30	Jackson Hall 115	CS313 - Intermediate Computer Programming	Section B
Tuesday	Lecture	08:00	09:30	Jackson Hall 115	CS330 - Hardware and Systems Fundamentals	Section A
Thursday	Lab	08:00	09:30	Jackson Hall 115	CS330 - Hardware and Systems Fundamentals	Section A
Tuesday	Lecture	09:45	11:15	Jackson Hall 115	CS330 - Hardware and Systems Fundamentals	Section B
Thursday	Lab	09:45	11:15	Jackson Hall 115	CS330 - Hardware and Systems Fundamentals	Section B
Tuesday	Lecture	13:15	14:45	D-Lab 102	CS331 - Computer Organization and Architecture	Section A
Thursday	Lecture	13:15	14:45	D-Lab 102	CS331 - Computer Organization and Architecture	Section A
Friday	Lab	12:15	13:45	Science Lab	CS331 - Computer Organization and Architecture	Section A
Monday	Lecture	08:00	09:30	Jackson Lab 221	CS341 - Web Technologies	Section A
Wednesday	Lecture	08:00	09:30	Jackson Lab 221	CS341 - Web Technologies	Section A
Friday	Lab	10:20	11:50	Jackson Lab 221	CS341 - Web Technologies	Section A
Monday	Lecture	09:45	11:15	Jackson Lab 221	CS341 - Web Technologies	Section B
Wednesday	Lecture	09:45	11:15	Jackson Lab 221	CS341 - Web Technologies	Section B
Friday	Lab	12:15	13:45	Jackson Lab 221	CS341 - Web Technologies	Section B
Monday	Lecture	11:30	13:00	Jackson Lab 221	CS341 - Web Technologies	Section C
Wednesday	Lecture	11:30	13:00	Jackson Lab 221	CS341 - Web Technologies	Section C
Friday	Lab	13:55	15:25	Jackson Lab 221	CS341 - Web Technologies	Section C
Monday	Seminar	13:15	14:45	Nutor Hall 100	CS410-SEM - CSIS Capstone Seminar	Section A
Tuesday	Lecture	13:15	14:45	Jackson Lab 221	CS413 - Concepts of Programming Languages	Section A
Thursday	Lecture	13:15	14:45	Jackson Lab 221	CS413 - Concepts of Programming Languages	Section A
Friday	Discussion	13:55	15:25	Jackson Hall 116	CS413 - Concepts of Programming Languages	Section A
Monday	Lecture	08:00	09:30	Norton-Motulsky 207A	CS433 - Operating Systems / Operating Systems and Systems Administration	Section A
Wednesday	Lecture	08:00	09:30	Norton-Motulsky 207A	CS433 - Operating Systems / Operating Systems and Systems Administration	Section A
Friday	Lab	13:55	15:25	D-Lab 102	CS433 - Operating Systems / Operating Systems and Systems Administration	Section A
Monday	Lecture	09:45	11:15	Norton-Motulsky 207A	CS433 - Operating Systems / Operating Systems and Systems Administration	Section B
Wednesday	Lecture	09:45	11:15	Norton-Motulsky 207A	CS433 - Operating Systems / Operating Systems and Systems Administration	Section B
Friday	Lab	12:15	13:45	D-Lab 102	CS433 - Operating Systems / Operating Systems and Systems Administration	Section B
Tuesday	Lecture	09:45	11:15	Jackson Lab 222	CS442 - E-Commerce	Section A
Thursday	Lecture	09:45	11:15	Jackson Lab 222	CS442 - E-Commerce	Section A
Friday	Lab	12:15	13:45	Jackson Lab 222	CS442 - E-Commerce	Section A
Monday	Lecture	08:00	09:30	Nutor Hall 100	CS456 - Algorithm Design and Analysis	Section A
Wednesday	Lecture	08:00	09:30	Nutor Hall 100	CS456 - Algorithm Design and Analysis	Section A
Friday	Lab	10:20	11:50	Nutor Hall 115	CS456 - Algorithm Design and Analysis	Section A
Monday	Lecture	09:45	11:15	Nutor Hall 100	CS456 - Algorithm Design and Analysis	Section B
Wednesday	Lecture	09:45	11:15	Nutor Hall 100	CS456 - Algorithm Design and Analysis	Section B
Friday	Lab	08:30	10:00	Nutor Hall 115	CS456 - Algorithm Design and Analysis	Section B
Monday	Lecture	15:00	16:30	Fab Lab 203	CS458 - Internet of Things	Section A
Tuesday	Lecture	09:45	11:15	Fab Lab 203	CS458 - Internet of Things	Section A
Thursday	Lecture	09:45	11:15	Fab Lab 203	CS458 - Internet of Things	Section A
Tuesday	Lecture	15:00	16:30	Jackson Lab 221	CS462 - Cloud Computing	Section A
Thursday	Lecture	15:00	16:30	Jackson Lab 221	CS462 - Cloud Computing	Section A
Friday	Lab	10:20	11:50	D-Lab 102	CS462 - Cloud Computing	Section A
Tuesday	Lecture	11:30	13:00	Jackson Lab 221	CS464 - Deep Learning	Section A
Wednesday	Lab	11:30	13:00	Jackson Lab 222	CS464 - Deep Learning	Section A
Thursday	Lecture	11:30	13:00	Jackson Lab 221	CS464 - Deep Learning	Section A
Monday	Lecture	09:45	11:15	Jackson Hall 115	ECON100 - Principles of Economics	Section B
Wednesday	Lecture	09:45	11:15	Jackson Hall 115	ECON100 - Principles of Economics	Section B
Friday	Discussion	09:10	10:10	Jackson Hall 116	ECON100 - Principles of Economics	Section B
Monday	Lecture	11:30	13:00	Jackson Hall 116	ECON100 - Principles of Economics	Section C
Wednesday	Lecture	11:30	13:00	Jackson Hall 116	ECON100 - Principles of Economics	Section C
Friday	Discussion	09:10	10:10	Jackson Hall 115	ECON100 - Principles of Economics	Section C
Tuesday	Lecture	15:00	16:30	Nutor Hall 100	ECON100 - Principles of Economics	Section D
Thursday	Lecture	15:00	16:30	Nutor Hall 100	ECON100 - Principles of Economics	Section D
Friday	Discussion	09:10	10:10	Nutor Hall 100	ECON100 - Principles of Economics	Section D
Monday	Lecture	08:00	09:30	Jackson Hall 115	ECON100 - Principles of Economics	Section A
Wednesday	Lecture	08:00	09:30	Jackson Hall 115	ECON100 - Principles of Economics	Section A
Friday	Discussion	08:00	09:00	Jackson Hall 115	ECON100 - Principles of Economics	Section A
Monday	Lecture	09:45	11:15	Jackson Lab 222	ECON201 - Principles of Microeconomics	Section B
Wednesday	Lecture	09:45	11:15	Jackson Lab 222	ECON201 - Principles of Microeconomics	Section B
Friday	Discussion	12:15	13:15	Norton-Motulsky 207A	ECON201 - Principles of Microeconomics	Section B
Monday	Lecture	11:30	13:00	Jackson Hall 115	ECON201 - Principles of Microeconomics	Section C
Wednesday	Lecture	11:30	13:00	Jackson Hall 115	ECON201 - Principles of Microeconomics	Section C
Friday	Discussion	13:55	14:55	Apt Hall 216	ECON201 - Principles of Microeconomics	Section C
Monday	Lecture	08:00	09:30	Apt Hall 216	ECON201 - Principles of Microeconomics	Section A
Wednesday	Lecture	08:00	09:30	Apt Hall 216	ECON201 - Principles of Microeconomics	Section A
Friday	Discussion	10:20	11:20	Norton-Motulsky 207A	ECON201 - Principles of Microeconomics	Section A
Monday	Lecture	11:30	13:00	Apt Hall 216	ECON231 - Mathematics for Economists	Section A
Wednesday	Lecture	11:30	13:00	Apt Hall 216	ECON231 - Mathematics for Economists	Section A
Friday	Discussion	12:15	13:15	Apt Hall 216	ECON231 - Mathematics for Economists	Section A
Tuesday	Lecture	09:45	11:15	Jackson Lab 221	ECON301 - Intermediate Microeconomic Theory I	Section A
Thursday	Lecture	09:45	11:15	Jackson Lab 221	ECON301 - Intermediate Microeconomic Theory I	Section A
Friday	Discussion	13:55	14:55	Norton-Motulsky 207A	ECON301 - Intermediate Microeconomic Theory I	Section A
Monday	Lecture	09:45	11:15	Apt Hall 216	ECON303 - Intermediate Macroeconomic Theory I	Section A
Wednesday	Lecture	09:45	11:15	Apt Hall 216	ECON303 - Intermediate Macroeconomic Theory I	Section A
Friday	Discussion	10:20	11:20	Apt Hall 216	ECON303 - Intermediate Macroeconomic Theory I	Section A
Tuesday	Lecture	13:15	14:45	Nutor Hall 100	ECON451 - Development Economics	Section A
Thursday	Lecture	13:15	14:45	Nutor Hall 100	ECON451 - Development Economics	Section A
Friday	Discussion	08:00	09:00	Nutor Hall 100	ECON451 - Development Economics	Section A
Monday	Lab	08:00	10:00	Fab Lab 203	EE320 - Signals & Systems	Section A
Wednesday	Lecture	08:00	09:30	Fab Lab 203	EE320 - Signals & Systems	Section A
Friday	Lecture	13:55	15:25	Fab Lab 203	EE320 - Signals & Systems	Section A
Monday	Lab	15:00	17:00	EE lab	EE341 - AC Electrical Machines	Section A
Wednesday	Lecture	11:30	13:00	EE lab	EE341 - AC Electrical Machines	Section A
Friday	Lecture	12:15	13:45	EE lab	EE341 - AC Electrical Machines	Section A
Monday	Lab	12:45	14:45	Fab Lab 203	EE421 - Digital and Analog Signal Processing in Telecommunications	Section A
Wednesday	Lecture	09:45	11:15	Fab Lab 203	EE421 - Digital and Analog Signal Processing in Telecommunications	Section A
Friday	Lecture	12:15	13:45	Fab Lab 203	EE421 - Digital and Analog Signal Processing in Telecommunications	Section A
Monday	Lab	08:00	10:00	EE lab	EE451 - Power Engineering	Section A
Wednesday	Lecture	13:15	14:45	EE lab	EE451 - Power Engineering	Section A
Friday	Lecture	13:55	15:25	EE lab	EE451 - Power Engineering	Section A
Monday	Lab	12:45	14:45	EE lab	EE453 - Power Systems Analysis	Section A
Wednesday	Lecture	08:00	09:30	EE lab	EE453 - Power Systems Analysis	Section A
Friday	Lecture	10:20	11:50	EE lab	EE453 - Power Systems Analysis	Section A
Thursday	Lecture	15:00	16:30	Fab Lab 203	ENGR212 - Instrumentation for Engineering	Section A
Friday	Lab	08:00	10:00	Fab Lab 203	ENGR212-LAB - Instrumentation for Engineering - LAB	Section A
Friday	Lab	10:10	12:10	Fab Lab 203	ENGR212-LAB - Instrumentation for Engineering - LAB	Section B
Monday	Lab	10:10	12:10	Fab Lab 303	ENGR311 - System Dynamics	Section A
Tuesday	Lecture	09:45	11:15	Fab Lab 303	ENGR311 - System Dynamics	Section A
Thursday	Lecture	09:45	11:15	Fab Lab 303	ENGR311 - System Dynamics	Section A
Wednesday	Seminar	15:00	16:30	Fab Lab 303	ENGR401-SEM - Engineering Capstone Seminar	Section A
Tuesday	Lecture	08:00	09:30	Jackson Lab 222	IS351 - Systems Analysis and Design	Section A
Thursday	Lecture	08:00	09:30	Jackson Lab 222	IS351 - Systems Analysis and Design	Section A
Friday	Lab	13:55	15:25	Jackson Lab 222	IS351 - Systems Analysis and Design	Section A
Monday	Lecture	15:00	16:30	Apt Hall 216	IS451 - Information and Systems Security	Section A
Wednesday	Lecture	15:00	16:30	Apt Hall 216	IS451 - Information and Systems Security	Section A
Thursday	Lab	11:30	13:00	Nutor Hall 115	IS451 - Information and Systems Security	Section A
Monday	Lecture	08:00	09:30	Jackson Lab 222	MATH121 - Pre-Calculus I	Section A
Tuesday	Lecture	09:45	11:15	Jackson Hall 116	MATH121 - Pre-Calculus I	Section A
Thursday	Lecture	09:45	11:15	Jackson Hall 116	MATH121 - Pre-Calculus I	Section A
Friday	Discussion	10:20	11:50	Science Lab	MATH121 - Pre-Calculus I	Section A
Monday	Lecture	08:00	09:30	Jackson Hall 116	MATH122 - Pre-Calculus II	Section A
Tuesday	Lecture	08:00	09:30	Apt Hall 216	MATH122 - Pre-Calculus II	Section A
Wednesday	Lecture	08:00	09:30	Jackson Hall 116	MATH122 - Pre-Calculus II	Section A
Friday	Discussion	13:55	15:25	Jackson Hall 115	MATH122 - Pre-Calculus II	Section A
Monday	Lecture	09:45	11:15	Jackson Hall 116	MATH122 - Pre-Calculus II	Section B
Tuesday	Lecture	09:45	11:15	Apt Hall 216	MATH122 - Pre-Calculus II	Section B
Wednesday	Lecture	09:45	11:15	Jackson Hall 116	MATH122 - Pre-Calculus II	Section B
Friday	Discussion	12:15	13:45	Jackson Hall 115	MATH122 - Pre-Calculus II	Section B
Monday	Lecture	13:15	14:45	Jackson Lab 221	MATH145 - Applied Calculus - Part I	Section A
Wednesday	Lecture	13:15	14:45	Jackson Lab 221	MATH145 - Applied Calculus - Part I	Section A
Friday	Discussion	10:20	11:50	Jackson Hall 116	MATH145 - Applied Calculus - Part I	Section A
Monday	Lecture	15:00	16:30	Jackson Lab 221	MATH145 - Applied Calculus - Part I	Section B
Wednesday	Lecture	15:00	16:30	Jackson Lab 221	MATH145 - Applied Calculus - Part I	Section B
Friday	Discussion	12:15	13:45	Jackson Hall 116	MATH145 - Applied Calculus - Part I	Section B
Tuesday	Lecture	13:15	14:45	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section A
Thursday	Lecture	13:15	14:45	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section A
Friday	Discussion	12:15	13:45	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section A
Tuesday	Lecture	15:00	16:30	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section B
Thursday	Lecture	15:00	16:30	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section B
Friday	Discussion	13:55	15:25	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section B
Monday	Lecture	15:00	16:30	Jackson Lab 222	MATH211 - Multivariable Calculus and Linear Algebra	Section A
Wednesday	Lecture	15:00	16:30	Jackson Lab 222	MATH211 - Multivariable Calculus and Linear Algebra	Section A
Friday	Discussion	10:20	11:50	Jackson Lab 222	MATH211 - Multivariable Calculus and Linear Algebra	Section A
Monday	Discussion	13:15	14:45	Databank Foundation Hall 218	MATH221 - Statistics	Section A
Tuesday	Lecture	08:00	09:30	Databank Foundation Hall 218	MATH221 - Statistics	Section A
Thursday	Lecture	08:00	09:30	Databank Foundation Hall 218	MATH221 - Statistics	Section A
Monday	Discussion	15:00	16:30	Databank Foundation Hall 218	MATH221 - Statistics	Section B
Tuesday	Lecture	09:45	11:15	Databank Foundation Hall 218	MATH221 - Statistics	Section B
Thursday	Lecture	09:45	11:15	Databank Foundation Hall 218	MATH221 - Statistics	Section B
Monday	Discussion	13:15	14:45	Apt Hall 217	MATH221 - Statistics	Section C
Tuesday	Lecture	11:30	13:00	Databank Foundation Hall 218	MATH221 - Statistics	Section C
Thursday	Lecture	11:30	13:00	Databank Foundation Hall 218	MATH221 - Statistics	Section C
Monday	Lecture	15:00	16:30	Apt Hall 217	MATH221 - Statistics	Section D
Tuesday	Lecture	13:15	14:45	Databank Foundation Hall 218	MATH221 - Statistics	Section D
Thursday	Discussion	13:15	14:45	Databank Foundation Hall 218	MATH221 - Statistics	Section D
Monday	Discussion	13:15	14:45	Apt Hall 216	MATH221 - Statistics	Section E
Tuesday	Lecture	08:00	09:30	Jackson Hall 116	MATH221 - Statistics	Section E
Thursday	Lecture	08:00	09:30	Jackson Hall 116	MATH221 - Statistics	Section E
Monday	Lab	15:00	17:00	Fab Lab 303	ME212 - Thermodynamics	Section A
Wednesday	Lecture	08:00	09:30	Fab Lab 303	ME212 - Thermodynamics	Section A
Friday	Lecture	08:00	09:30	Fab Lab 303	ME212 - Thermodynamics	Section A
Monday	Lab	12:45	14:45	Fab Lab 303	ME311 - Mechanics of Materials	Section A
Wednesday	Lecture	09:45	11:15	Bio Lab	ME311 - Mechanics of Materials	Section A
Friday	Lecture	13:55	15:25	Bio Lab	ME311 - Mechanics of Materials	Section A
Monday	Lab	15:00	17:00	Science Lab	ME401 - Mechanics of Machines & Engineering Vibration	Section A
Wednesday	Lecture	13:15	14:45	Fab Lab 303	ME401 - Mechanics of Machines & Engineering Vibration	Section A
Friday	Lecture	10:20	11:50	Fab Lab 303	ME401 - Mechanics of Machines & Engineering Vibration	Section A
Monday	Lab	08:00	10:00	Science Lab	ME422 - Heat Transfer	Section A
Tuesday	Lecture	08:00	09:30	Science Lab	ME422 - Heat Transfer	Section A
Wednesday	Lecture	08:00	09:30	Science Lab	ME422 - Heat Transfer	Section A
Monday	Lab	11:30	13:30	D-Lab 102	ME434 - Hydraulic & Fluid Machinery	Section A
Tuesday	Lecture	09:45	11:15	EE lab	ME434 - Hydraulic & Fluid Machinery	Section A
Wednesday	Lecture	09:45	11:15	EE lab	ME434 - Hydraulic & Fluid Machinery	Section A
Monday	Lab	08:00	10:00	Fab Lab 303	ME442 - Computer Aided Design and Manufacturing	Section A
Tuesday	Lecture	08:00	09:30	Fab Lab 303	ME442 - Computer Aided Design and Manufacturing	Section A
Thursday	Lecture	08:00	09:30	Fab Lab 303	ME442 - Computer Aided Design and Manufacturing	Section A
Monday	Lecture	11:00	14:00	Bio Lab	ME444 - Advanced Mechanical Machine Design	Section A
Tuesday	Lab	09:45	11:45	Bio Lab	ME444 - Advanced Mechanical Machine Design	Section A
Tuesday	Lecture	11:30	13:00	Nutor Hall 100	POLS221 - African Philosophical Thought	Section A
Wednesday	Discussion	16:45	17:45	Nutor Hall 115	POLS221 - African Philosophical Thought	Section A
Thursday	Lecture	11:30	13:00	Nutor Hall 100	POLS221 - African Philosophical Thought	Section A
Tuesday	Lecture	11:30	13:00	Jackson Lab 222	POLS234 - Comparative Politics	Section A
Thursday	Lecture	11:30	13:00	Jackson Lab 222	POLS234 - Comparative Politics	Section A
Friday	Discussion	09:10	10:10	Apt Hall 216	POLS234 - Comparative Politics	Section A
Tuesday	Lecture	13:15	14:45	Apt Hall 216	POLS237 - African Trade and Regional Integration	Section A
Thursday	Lecture	13:15	14:45	Apt Hall 216	POLS237 - African Trade and Regional Integration	Section A
Friday	Discussion	08:00	09:00	Apt Hall 217	POLS237 - African Trade and Regional Integration	Section A
Monday	Lab	12:45	14:45	Science Lab	SC113 - Physics: Electromagnetism	Section A
Wednesday	Lecture	09:45	11:15	Science Lab	SC113 - Physics: Electromagnetism	Section A
Thursday	Lecture	09:45	11:15	Science Lab	SC113 - Physics: Electromagnetism	Section A
Monday	Lab	10:10	12:10	Science Lab	SC113 - Physics: Electromagnetism	Section B
Wednesday	Lecture	11:30	13:00	Science Lab	SC113 - Physics: Electromagnetism	Section B
Thursday	Lecture	11:30	13:00	Science Lab	SC113 - Physics: Electromagnetism	Section B
Tuesday	Lecture	15:00	16:30	Jackson Hall 116	SOAN 322 - African Cultural Institutions	Section A
Thursday	Lecture	15:00	16:30	Jackson Hall 116	SOAN 322 - African Cultural Institutions	Section A
Friday	Discussion	09:10	10:10	Jackson Lab 222	SOAN 322 - African Cultural Institutions	Section A
Monday	Seminar	13:15	14:45	Nutor Hall 115	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section A
Wednesday	Discussion	13:45	14:45	Apt Hall 216	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section A
Tuesday	Seminar	09:45	11:15	Nutor Hall 100	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section B
Wednesday	Discussion	16:45	17:45	Jackson Hall 115	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section B
Tuesday	Seminar	11:30	13:00	Nutor Hall 115	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section C
Wednesday	Discussion	15:00	16:00	D-Lab 102	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section C
Wednesday	Discussion	13:45	14:45	Jackson Lab 222	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section D
Thursday	Seminar	11:30	13:00	Apt Hall 216	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section D
Wednesday	Discussion	15:00	16:00	Nutor Hall 100	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section E
Thursday	Seminar	13:15	14:45	Apt Hall 217	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section E
Tuesday	Seminar	08:00	09:30	Nutor Hall 100	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section F
Wednesday	Discussion	16:45	17:45	Radichel MPR	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section F
Monday	Seminar	13:15	14:45	Jackson Lab 222	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section G
Wednesday	Discussion	13:45	14:45	Radichel MPR	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section G
Tuesday	Seminar	15:00	16:30	Apt Hall 216	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section H
Wednesday	Discussion	13:45	14:45	Nutor Hall 100	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section H
Monday	Seminar	15:00	16:30	Nutor Hall 216	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section I
Wednesday	Discussion	15:00	16:00	Jackson Hall 115	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section I
Monday	Seminar	15:00	16:30	Nutor Hall 100	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section J
Wednesday	Discussion	15:00	16:00	Nutor Hall 216	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section J
Tuesday	Lecture	13:15	14:45	Jackson Hall 116	SOAN227 - Religion in Africa	Section A
Thursday	Lecture	13:15	14:45	Jackson Hall 116	SOAN227 - Religion in Africa	Section A
Friday	Discussion	08:00	09:00	Apt Hall 216	SOAN227 - Religion in Africa	Section A
Tuesday	Lecture	15:00	16:30	Norton-Motulsky 207A	SOAN234 - African Music and the Contemporary Art Music Scene	Section A
Thursday	Lecture	15:00	16:30	Norton-Motulsky 207A	SOAN234 - African Music and the Contemporary Art Music Scene	Section A
Friday	Discussion	09:10	10:10	D-Lab 102	SOAN234 - African Music and the Contemporary Art Music Scene	Section A
Tuesday	Lecture	11:30	13:00	Nutor Hall 216	SOAN237 - Crafting Cultures: Exploring African Cultures Through Ceramics and Pottery	Section A
Thursday	Lecture	11:30	13:00	Nutor Hall 216	SOAN237 - Crafting Cultures: Exploring African Cultures Through Ceramics and Pottery	Section A
Friday	Discussion	08:00	09:00	Databank Foundation Hall 218	SOAN237 - Crafting Cultures: Exploring African Cultures Through Ceramics and Pottery	Section A
Tuesday	Lecture	13:15	14:45	Jackson Lab 222	SOAN238 - Introduction to Sociocultural Anthropology	Section A
Thursday	Lecture	13:15	14:45	Jackson Lab 222	SOAN238 - Introduction to Sociocultural Anthropology	Section A
Friday	Discussion	08:00	09:00	Jackson Lab 222	SOAN238 - Introduction to Sociocultural Anthropology	Section A
Tuesday	Lecture	11:30	13:00	D-Lab 102	SOAN240 - Neo-Traditional African Dance Forms	Section A
Wednesday	Discussion	16:45	17:45	D-Lab 102	SOAN240 - Neo-Traditional African Dance Forms	Section A
Thursday	Lecture	11:30	13:00	D-Lab 102	SOAN240 - Neo-Traditional African Dance Forms	Section A
Tuesday	Lecture	16:45	18:15	Jackson Hall 116	SOAN328 - Creative and Research Internship	Section A
Tuesday	Lecture	13:15	14:45	Nutor Hall 115	SOAN331 - Climate Change and Global Innovation	Section A
Thursday	Lecture	13:15	14:45	Nutor Hall 115	SOAN331 - Climate Change and Global Innovation	Section A
Friday	Discussion	08:00	09:00	Jackson Lab 221	SOAN331 - Climate Change and Global Innovation	Section A
Tuesday	Seminar	13:15	14:45	Norton-Motulsky 207A	SOAN411 - Leadership Seminar IV: Leadership as Service	Section A
Thursday	Seminar	13:15	14:45	Norton-Motulsky 207A	SOAN411 - Leadership Seminar IV: Leadership as Service	Section A
Tuesday	Seminar	15:00	16:30	Jackson Lab 222	SOAN411 - Leadership Seminar IV: Leadership as Service	Section B
Thursday	Seminar	15:00	16:30	Jackson Lab 222	SOAN411 - Leadership Seminar IV: Leadership as Service	Section B
Tuesday	Seminar	15:00	16:30	Nutor Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section C
Thursday	Seminar	15:00	16:30	Nutor Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section C
Monday	Seminar	15:00	16:30	Nutor Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section D
Wednesday	Seminar	15:00	16:30	Nutor Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section D
Tuesday	Seminar	15:00	16:30	Apt Hall 217	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section A
Wednesday	Seminar	15:00	16:30	Apt Hall 217	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section A
Tuesday	Seminar	13:15	14:45	Apt Hall 217	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section B
Wednesday	Seminar	13:15	14:45	Apt Hall 217	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section B