-- This file was generated by update.py on 2025-03-12 14:42:29
DELETE FROM public.timetable;

COPY public.timetable (day, period_name, start_time, end_time, location, course_code, section) FROM stdin;
Monday	Discussion	13:15	14:45	Bio Lab	AS111 - Ashesi Success	Section A
Monday	Discussion	15:00	16:30	Norton-Motulsky 207A	AS111 - Ashesi Success	Section B
Wednesday	Discussion	08:00	09:30	Jackson Hall 116	AS111 - Ashesi Success	Section C
Wednesday	Discussion	11:30	13:00	Fab Lab 203	AS111 - Ashesi Success	Section D
Wednesday	Discussion	11:30	13:00	Fab Lab 303	AS111 - Ashesi Success	Section E
Thursday	Discussion	08:00	09:30	Norton-Motulsky 207B	AS111 - Ashesi Success	Section F
Thursday	Discussion	09:45	11:15	Fab Lab 203	AS111 - Ashesi Success	Section G
Monday	Discussion	16:45	18:15	Jackson Hall 115	AS111 - Ashesi Success	Section H
Monday	Discussion	16:45	18:15	Jackson Hall 116	AS111 - Ashesi Success	Section I
Monday	Discussion	16:45	18:15	Radichel MPR	AS111 - Ashesi Success	Section J
Monday	Discussion	16:45	18:15	Apt Hall 216	AS111 - Ashesi Success	Section K
Monday	Discussion	16:45	18:15	Apt Hall 217	AS111 - Ashesi Success	Section L
Wednesday	Discussion	16:45	18:15	Jackson Hall 115	AS111 - Ashesi Success	Section M
Wednesday	Discussion	16:45	18:15	Jackson Hall 116	AS111 - Ashesi Success	Section N
Wednesday	Discussion	16:45	18:15	Radichel MPR	AS111 - Ashesi Success	Section O
Thursday	Discussion	16:45	18:15	Jackson Hall 115	AS111 - Ashesi Success	Section P
Thursday	Discussion	16:45	18:15	Jackson Hall 116	AS111 - Ashesi Success	Section Q
Thursday	Discussion	16:45	18:15	Radichel MPR	AS111 - Ashesi Success	Section R
Thursday	Discussion	16:45	18:15	Apt Hall 216	AS111 - Ashesi Success	Section S
Thursday	Discussion	16:45	18:15	Apt Hall 217	AS111 - Ashesi Success	Section T
Tuesday	Meeting	08:00	09:30	King Eng. Lab 102	AV100 - Ashesi Voices	Section A
Thursday	Lecture	08:00	09:30	King Eng. Lab 102	AV100 - Ashesi Voices	Section A
Tuesday	Lecture	13:15	14:45	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section A
Thursday	Lecture	13:15	14:45	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section A
Friday	Discussion	08:00	09:00	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section A
Tuesday	Lecture	11:30	13:00	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section B
Thursday	Discussion	11:30	13:00	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section B
Friday	Discussion	09:10	10:10	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section B
Tuesday	Lecture	15:00	16:30	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section C
Thursday	Lecture	15:00	16:30	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section C
Friday	Discussion	09:10	10:10	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section C
Tuesday	Lecture	15:00	16:30	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section D
Thursday	Lecture	15:00	16:30	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section D
Friday	Discussion	09:10	10:10	Nutor Hall 115	BUSA161 - Foundations of Design and Entrepreneurship I	Section D
Tuesday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section E
Thursday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section E
Friday	Discussion	08:00	09:00	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section E
Tuesday	Lecture	11:30	13:00	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section F
Thursday	Lecture	11:30	13:00	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section F
Friday	Discussion	08:00	09:00	Fab Lab 203	BUSA161 - Foundations of Design and Entrepreneurship I	Section F
Tuesday	Lecture	13:15	14:45	Nutor Hall 115	BUSA161 - Foundations of Design and Entrepreneurship I	Section G
Thursday	Lecture	13:15	14:45	Nutor Hall 115	BUSA161 - Foundations of Design and Entrepreneurship I	Section G
Friday	Discussion	08:00	09:00	Nutor Hall 115	BUSA161 - Foundations of Design and Entrepreneurship I	Section G
Tuesday	Lecture	13:15	14:45	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section H
Thursday	Lecture	13:15	14:45	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section H
Friday	Discussion	09:10	10:10	Fab Lab 203	BUSA161 - Foundations of Design and Entrepreneurship I	Section H
Monday	Lecture	08:00	09:30	Nutor Hall 216	BUSA220 - Introduction to Finance	Section A
Wednesday	Lecture	08:00	09:30	Nutor Hall 216	BUSA220 - Introduction to Finance	Section A
Friday	Discussion	10:20	11:20	Nutor Hall 216	BUSA220 - Introduction to Finance	Section A
Monday	Lecture	09:45	11:15	Nutor Hall 216	BUSA220 - Introduction to Finance	Section B
Wednesday	Lecture	09:45	11:15	Nutor Hall 216	BUSA220 - Introduction to Finance	Section B
Friday	Discussion	12:15	13:15	Nutor Hall 216	BUSA220 - Introduction to Finance	Section B
Monday	Lecture	11:30	13:00	Nutor Hall 216	BUSA220 - Introduction to Finance	Section C
Wednesday	Lecture	11:30	13:00	Nutor Hall 216	BUSA220 - Introduction to Finance	Section C
Friday	Discussion	13:55	14:55	Nutor Hall 216	BUSA220 - Introduction to Finance	Section C
Monday	Lecture	08:00	09:30	Databank Foundation Hall 218	BUSA311 - Managerial Accounting	Section A
Wednesday	Lecture	08:00	09:30	Databank Foundation Hall 218	BUSA311 - Managerial Accounting	Section A
Friday	Discussion	12:15	13:15	Databank Foundation Hall 218	BUSA311 - Managerial Accounting	Section A
Monday	Lecture	11:30	13:00	Nutor Hall 115	BUSA311 - Managerial Accounting	Section B
Wednesday	Lecture	11:30	13:00	Nutor Hall 115	BUSA311 - Managerial Accounting	Section B
Friday	Discussion	13:55	14:55	Databank Foundation Hall 218	BUSA311 - Managerial Accounting	Section B
Friday	Independent Study	16:45	18:15	 - 	BUSA321 - Investments	Section A
Tuesday	Lecture	13:15	14:45	Nutor Hall 216	BUSA341 - Marketing	Section A
Wednesday	Discussion	15:00	16:00	Nutor Hall 216	BUSA341 - Marketing	Section A
Thursday	Lecture	13:15	14:45	Nutor Hall 216	BUSA341 - Marketing	Section A
Tuesday	Lecture	15:00	16:30	Nutor Hall 216	BUSA341 - Marketing	Section B
Wednesday	Discussion	16:40	17:40	Nutor Hall 216	BUSA341 - Marketing	Section B
Thursday	Lecture	15:00	16:30	Nutor Hall 216	BUSA341 - Marketing	Section B
Friday	Independent Study	16:45	18:15	 - 	BUSA350 - International Trade and Policy	Section A
Monday	Seminar	08:00	09:30	Norton-Motulsky 207B	BUSA401_B - Entrepreneurship II	Section A
Wednesday	Lecture	09:45	13:00	Norton-Motulsky 207B	BUSA401_B - Entrepreneurship II	Section A
Tuesday	Lecture	08:00	09:30	Apt Hall 217	BUSA402 - Business Law	Section A
Thursday	Lecture	08:00	09:30	Apt Hall 217	BUSA402 - Business Law	Section A
Friday	Discussion	08:00	09:00	Jackson Hall 116	BUSA402 - Business Law	Section A
Tuesday	Lecture	09:45	11:15	Apt Hall 217	BUSA402 - Business Law	Section B
Thursday	Period	09:45	11:15	Apt Hall 217	BUSA402 - Business Law	Section B
Friday	Discussion	09:10	10:10	Jackson Hall 116	BUSA402 - Business Law	Section B
Monday	Discussion	08:30	09:30	Apt Hall 217	BUSA405 - Competitive Strategy	Section A
Tuesday	Lecture	09:45	11:15	Nutor Hall 216	BUSA405 - Competitive Strategy	Section A
Thursday	Lecture	09:45	11:15	Nutor Hall 216	BUSA405 - Competitive Strategy	Section A
Monday	Discussion	09:45	10:45	Apt Hall 217	BUSA405 - Competitive Strategy	Section B
Tuesday	Lecture	11:30	13:00	Nutor Hall 216	BUSA405 - Competitive Strategy	Section B
Thursday	Lecture	11:30	13:00	Nutor Hall 216	BUSA405 - Competitive Strategy	Section B
Monday	Discussion	11:30	12:30	Apt Hall 217	BUSA405 - Competitive Strategy	Section C
Tuesday	Lecture	13:15	14:45	Jackson Hall 115	BUSA405 - Competitive Strategy	Section C
Thursday	Lecture	13:15	14:45	Jackson Hall 115	BUSA405 - Competitive Strategy	Section C
Monday	Seminar	11:30	13:00	Radichel MPR	BUSA412 - Applied Project II (BA)	Section A
Wednesday	Seminar	11:30	13:00	Radichel MPR	BUSA412 - Applied Project II (BA)	Section A
Monday	Lecture	13:15	14:45	Nutor Hall 115	BUSA425 - Venture Capital Investment	Section A
Wednesday	Lecture	13:15	14:45	Nutor Hall 115	BUSA425 - Venture Capital Investment	Section A
Friday	Discussion	10:20	11:20	Norton-Motulsky 207B	BUSA425 - Venture Capital Investment	Section A
Tuesday	Lecture	13:15	14:45	Jackson Lab 221	BUSA430 - Human Resource Management	Section A
Thursday	Lecture	13:15	14:45	Jackson Lab 221	BUSA430 - Human Resource Management	Section A
Friday	Discussion	09:10	10:10	Nutor Hall 216	BUSA430 - Human Resource Management	Section A
Monday	Lecture	13:15	14:45	Radichel MPR	BUSA446 - Integrated Marketing Communications	Section A
Wednesday	Lecture	13:15	14:45	Radichel MPR	BUSA446 - Integrated Marketing Communications	Section A
Friday	Discussion	08:00	09:00	Radichel MPR	BUSA446 - Integrated Marketing Communications	Section A
Monday	Lecture	15:00	16:30	Radichel MPR	BUSA455 - Project Management	Section A
Wednesday	Lecture	15:00	16:30	Radichel MPR	BUSA455 - Project Management	Section A
Friday	Discussion	09:10	10:10	Radichel MPR	BUSA455 - Project Management	Section A
Tuesday	Lecture	11:30	13:00	Nutor Hall 115	BUSA458 - Data Analytics for Business	Section A
Thursday	Lecture	11:30	13:00	Nutor Hall 115	BUSA458 - Data Analytics for Business	Section A
Friday	Discussion	08:00	09:00	Nutor Hall 216	BUSA458 - Data Analytics for Business	Section A
Monday	Discussion	16:40	17:40	Norton-Motulsky 207B	BUSA462 - New Product Development	Section A
Tuesday	Lecture	15:00	16:30	Nutor Hall 115	BUSA462 - New Product Development	Section A
Thursday	Lecture	15:00	16:30	Nutor Hall 115	BUSA462 - New Product Development	Section A
Monday	Seminar	09:45	11:15	Nutor Hall 100	BUSA492 - Undergraduate Thesis II (BA)	Section A
Wednesday	Seminar	09:45	11:15	Nutor Hall 100	BUSA492 - Undergraduate Thesis II (BA)	Section A
Tuesday	Lecture	13:15	14:45	Fab Lab 303	CE122 - Applied Programming for Engineers	Section A
Thursday	Lab	13:15	14:45	Fab Lab 303	CE122 - Applied Programming for Engineers	Section A
Tuesday	Lecture	15:00	16:30	Fab Lab 303	CE122 - Applied Programming for Engineers	Section B
Thursday	Lab	15:00	16:30	Fab Lab 303	CE122 - Applied Programming for Engineers	Section B
Tuesday	Lecture	13:15	14:45	EE lab	CE322 - Digital Systems Design	Section A
Wednesday	Lab	09:00	11:00	Fab Lab 203	CE322 - Digital Systems Design	Section A
Friday	Lecture	08:10	09:40	EE lab	CE322 - Digital Systems Design	Section A
Monday	Lecture	08:00	09:30	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section A
Wednesday	Lecture	08:00	09:30	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section A
Friday	Lab	13:55	15:25	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section A
Monday	Lecture	09:45	11:15	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section B
Wednesday	Period	09:45	11:15	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section B
Friday	Lab	12:15	13:45	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section B
Monday	Lecture	11:30	13:00	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section C
Wednesday	Lecture	11:30	13:00	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section C
Friday	Lab	13:55	15:25	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section C
Monday	Lecture	13:15	14:45	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section D
Wednesday	Lecture	13:15	14:45	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section D
Friday	Lab	12:15	13:45	Norton-Motulsky 207A	CS111 - Introduction to Computing and Information Systems	Section D
Monday	Lecture	09:45	11:15	Jackson Lab 222	CS111 - Introduction to Computing and Information Systems	Section E
Wednesday	Lecture	09:45	11:15	Jackson Lab 222	CS111 - Introduction to Computing and Information Systems	Section E
Friday	Lab	10:20	11:50	Jackson Lab 221	CS111 - Introduction to Computing and Information Systems	Section E
Monday	Lecture	11:30	13:00	Jackson Lab 222	CS111 - Introduction to Computing and Information Systems	Section F
Wednesday	Lecture	11:30	13:00	Jackson Lab 222	CS111 - Introduction to Computing and Information Systems	Section F
Friday	Lab	13:55	15:25	Jackson Lab 222	CS111 - Introduction to Computing and Information Systems	Section F
Monday	Lecture	13:15	14:45	Jackson Lab 222	CS213 - Object-Oriented Programming	Section A
Wednesday	Lecture	13:15	14:45	Jackson Lab 222	CS213 - Object-Oriented Programming	Section A
Friday	Lab	13:55	15:25	Norton-Motulsky 207A	CS213 - Object-Oriented Programming	Section A
Monday	Lecture	13:15	14:45	Jackson Hall 116	CS222 - Data Structures and Algorithms	Section A
Wednesday	Lecture	13:15	14:45	Jackson Hall 116	CS222 - Data Structures and Algorithms	Section A
Friday	Lab	13:55	15:25	Apt Hall 217	CS222 - Data Structures and Algorithms	Section A
Monday	Lecture	15:00	16:30	Jackson Hall 116	CS222 - Data Structures and Algorithms	Section B
Wednesday	Lecture	15:00	16:30	Jackson Hall 116	CS222 - Data Structures and Algorithms	Section B
Friday	Lab	12:15	13:45	Apt Hall 217	CS222 - Data Structures and Algorithms	Section B
Tuesday	Lecture	11:30	13:00	Jackson Hall 115	CS222 - Data Structures and Algorithms	Section C
Thursday	Lecture	11:30	13:00	Jackson Hall 115	CS222 - Data Structures and Algorithms	Section C
Friday	Lab	13:55	15:25	Apt Hall 216	CS222 - Data Structures and Algorithms	Section C
Tuesday	Lecture	11:30	13:00	Apt Hall 217	CS254 - Introduction to Artificial Intelligence	Section A
Wednesday	Lab	08:00	09:30	Apt Hall 217	CS254 - Introduction to Artificial Intelligence	Section A
Thursday	Lecture	11:30	13:00	Apt Hall 217	CS254 - Introduction to Artificial Intelligence	Section A
Tuesday	Lecture	13:15	14:45	Apt Hall 217	CS254 - Introduction to Artificial Intelligence	Section B
Wednesday	Lab	09:45	11:15	Apt Hall 217	CS254 - Introduction to Artificial Intelligence	Section B
Thursday	Lecture	13:15	14:45	Apt Hall 217	CS254 - Introduction to Artificial Intelligence	Section B
Tuesday	Lecture	15:00	16:30	Apt Hall 217	CS254 - Introduction to Artificial Intelligence	Section C
Wednesday	Lab	11:30	13:00	Apt Hall 217	CS254 - Introduction to Artificial Intelligence	Section C
Thursday	Lecture	15:00	16:30	Apt Hall 217	CS254 - Introduction to Artificial Intelligence	Section C
Wednesday	Independent Study	16:45	18:15	 - 	CS254 - Introduction to Artificial Intelligence	Section D
Tuesday	Lecture	13:15	14:45	Science Lab	CS314 - Human Computer Interaction	Section A
Wednesday	Lab	08:00	09:30	Jackson Lab 222	CS314 - Human Computer Interaction	Section A
Thursday	Lecture	13:15	14:45	Science Lab	CS314 - Human Computer Interaction	Section A
Monday	Lecture	08:00	09:30	Apt Hall 216	CS323 - Database Systems / Database Management	Section A
Wednesday	Lecture	08:00	09:30	Apt Hall 216	CS323 - Database Systems / Database Management	Section A
Friday	Lab	08:40	10:10	Apt Hall 216	CS323 - Database Systems / Database Management	Section A
Monday	Lecture	09:45	11:15	Apt Hall 216	CS323 - Database Systems / Database Management	Section B
Wednesday	Lecture	09:45	11:15	Apt Hall 216	CS323 - Database Systems / Database Management	Section B
Friday	Lab	10:20	11:50	Apt Hall 216	CS323 - Database Systems / Database Management	Section B
Monday	Lecture	11:30	13:00	Apt Hall 216	CS323 - Database Systems / Database Management	Section C
Wednesday	Lecture	11:30	13:00	Apt Hall 216	CS323 - Database Systems / Database Management	Section C
Friday	Lab	12:15	13:45	Apt Hall 216	CS323 - Database Systems / Database Management	Section C
Monday	Lecture	08:00	09:30	King Eng. Lab 102	CS331 - Computer Organization and Architecture	Section A
Wednesday	Lecture	08:00	09:30	King Eng. Lab 102	CS331 - Computer Organization and Architecture	Section A
Friday	Lab	08:40	10:10	King Eng. Lab 102	CS331 - Computer Organization and Architecture	Section A
Monday	Lecture	09:45	11:15	King Eng. Lab 102	CS331 - Computer Organization and Architecture	Section B
Wednesday	Lecture	09:45	11:15	King Eng. Lab 102	CS331 - Computer Organization and Architecture	Section B
Friday	Lab	10:20	11:50	King Eng. Lab 102	CS331 - Computer Organization and Architecture	Section B
Tuesday	Lecture	11:30	13:00	Jackson Lab 222	CS353 - Introduction to AI Robotics	Section A
Thursday	Lecture	11:30	13:00	Jackson Lab 222	CS353 - Introduction to AI Robotics	Section A
Friday	Lab	10:20	11:50	Jackson Lab 222	CS353 - Introduction to AI Robotics	Section A
Tuesday	Lecture	15:00	16:30	King Eng. Lab 102	CS354 - Computer Game Development	Section A
Thursday	Lecture	15:00	16:30	King Eng. Lab 102	CS354 - Computer Game Development	Section A
Friday	Lab	13:55	15:25	King Eng. Lab 102	CS354 - Computer Game Development	Section A
Tuesday	Lecture	13:15	14:45	Jackson Lab 222	CS361 - Introduction to Modelling & Simulation	Section A
Thursday	Lab	13:15	14:45	Jackson Lab 222	CS361 - Introduction to Modelling & Simulation	Section A
Tuesday	Lecture	15:00	16:30	Jackson Lab 222	CS361 - Introduction to Modelling & Simulation	Section B
Thursday	Lab	15:00	16:30	Jackson Lab 222	CS361 - Introduction to Modelling & Simulation	Section B
Monday	Set up for grading only	16:45	18:15	OT	CS410 - Applied Project (CS)	Section A
Monday	Set up for grading only	11:30	13:00	Nutor Hall 100	CS410-SEM - CSIS Capstone Seminar	Section A
Monday	Lab	13:15	14:45	Jackson Hall 115	CS415 - Software Engineering	Section A
Wednesday	Lecture	13:15	14:45	Jackson Hall 115	CS415 - Software Engineering	Section A
Friday	Period	12:15	13:45	Nutor Hall 100	CS415 - Software Engineering	Section A
Monday	Lab	15:00	16:30	Jackson Hall 115	CS415 - Software Engineering	Section B
Wednesday	Lecture	15:00	16:30	Jackson Hall 115	CS415 - Software Engineering	Section B
Friday	Discussion	13:55	15:25	Nutor Hall 100	CS415 - Software Engineering	Section B
Monday	Lecture	13:15	14:45	Nutor Hall 100	CS432 - Networks and Data Communication	Section A
Wednesday	Lecture	13:15	14:45	Nutor Hall 100	CS432 - Networks and Data Communication	Section A
Thursday	Lab	13:15	14:45	Nutor Hall 100	CS432 - Networks and Data Communication	Section A
Monday	Lecture	15:00	16:30	Nutor Hall 100	CS432 - Networks and Data Communication	Section B
Wednesday	Lecture	15:00	16:30	Nutor Hall 100	CS432 - Networks and Data Communication	Section B
Thursday	Lab	15:20	16:50	Nutor Hall 100	CS432 - Networks and Data Communication	Section B
Monday	Lab	09:45	11:15	 - 	CS433 - Operating Systems / Operating Systems and Systems Administration	Section A
Tuesday	Lecture	08:00	09:30	 - 	CS433 - Operating Systems / Operating Systems and Systems Administration	Section A
Thursday	Lecture	08:00	09:30	 - 	CS433 - Operating Systems / Operating Systems and Systems Administration	Section A
Tuesday	Lecture	11:30	13:00	Apt Hall 216	CS443 - Mobile Application Development / Mobile Web Programming	Section A
Thursday	Lecture	11:30	13:00	Apt Hall 216	CS443 - Mobile Application Development / Mobile Web Programming	Section A
Friday	Lab	10:20	11:50	Nutor Hall 100	CS443 - Mobile Application Development / Mobile Web Programming	Section A
Tuesday	Lecture	09:45	11:15	Jackson Lab 221	CS461 - Data Science	Section A
Thursday	Lecture	09:45	11:15	Jackson Lab 221	CS461 - Data Science	Section A
Friday	Lab	12:15	13:45	King Eng. Lab 102	CS461 - Data Science	Section A
Wednesday	Set up for grading only	16:45	18:15	OT	CS492 - Undergraduate Thesis II (CS)	Section A
Tuesday	Lecture	13:15	14:45	Bio Lab	ECON 302 - Intermediate Microeconomic Theory II	Section A
Thursday	Lecture	13:15	14:45	Bio Lab	ECON 302 - Intermediate Microeconomic Theory II	Section A
Friday	Discussion	14:25	15:25	Science Lab	ECON 302 - Intermediate Microeconomic Theory II	Section A
Monday	Lecture	11:30	13:00	Databank Foundation Hall 218	ECON 304 - Intermediate Macroeconomic Theory II	Section A
Wednesday	Lecture	11:30	13:00	Databank Foundation Hall 218	ECON 304 - Intermediate Macroeconomic Theory II	Section A
Friday	Discussion	10:20	11:20	Databank Foundation Hall 218	ECON 304 - Intermediate Macroeconomic Theory II	Section A
Monday	Lecture	13:15	14:45	Nutor Hall 216	ECON 321 - Econometrics I	Section A
Wednesday	Lecture	13:15	14:45	EE lab	ECON 321 - Econometrics I	Section A
Friday	Discussion	09:10	10:10	Bio Lab	ECON 321 - Econometrics I	Section A
Monday	Lecture	11:30	13:00	Jackson Hall 115	ECON202 - Principles of Macroeconomics	Section A
Wednesday	Lecture	11:30	13:00	Jackson Hall 115	ECON202 - Principles of Macroeconomics	Section A
Friday	Discussion	09:10	10:10	Databank Foundation Hall 218	ECON202 - Principles of Macroeconomics	Section A
Monday	Lecture	09:45	11:15	Databank Foundation Hall 218	ECON202 - Principles of Macroeconomics	Section B
Wednesday	Lecture	09:45	11:15	Databank Foundation Hall 218	ECON202 - Principles of Macroeconomics	Section B
Friday	Discussion	08:00	09:00	Databank Foundation Hall 218	ECON202 - Principles of Macroeconomics	Section B
Monday	Lecture	15:00	16:30	Nutor Hall 216	ECON211 - The Economy of Ghana	Section A
Wednesday	Lecture	15:00	16:30	Jackson Lab 222	ECON211 - The Economy of Ghana	Section A
Friday	Discussion	14:25	15:25	EE lab	ECON211 - The Economy of Ghana	Section A
Monday	Lecture	08:00	09:30	Bio Lab	ECON241 - Introduction to  Environmental Economics	Section A
Wednesday	Lecture	08:00	09:30	Norton-Motulsky 207B	ECON241 - Introduction to  Environmental Economics	Section A
Friday	Discussion	10:20	11:20	Norton-Motulsky 207A	ECON241 - Introduction to  Environmental Economics	Section A
Monday	Lab	15:00	17:00	Bio Lab	EE 422 - Advanced Communication Systems	Section A
Wednesday	Lecture	15:00	16:30	Fab Lab 203	EE 422 - Advanced Communication Systems	Section A
Friday	Lecture	12:15	13:45	Fab Lab 203	EE 422 - Advanced Communication Systems	Section A
Monday	Lecture	08:00	09:30	EE lab	EE222 - Circuits and Electronics	Section A
Wednesday	Lecture	08:00	09:30	EE lab	EE222 - Circuits and Electronics	Section A
Friday	Lab	09:50	11:50	EE lab	EE222 - Circuits and Electronics	Section A
Monday	Lecture	09:45	11:15	EE lab	EE222 - Circuits and Electronics	Section B
Wednesday	Lecture	09:45	11:15	EE lab	EE222 - Circuits and Electronics	Section B
Friday	Lab	12:15	14:15	EE lab	EE222 - Circuits and Electronics	Section B
Monday	Lab	10:10	12:10	Bio Lab	EE321 - Communication Systems	Section A
Wednesday	Lecture	13:15	14:45	Fab Lab 203	EE321 - Communication Systems	Section A
Friday	Lecture	13:55	15:25	Fab Lab 203	EE321 - Communication Systems	Section A
Tuesday	Lecture	08:00	09:30	Fab Lab 203	EE342 - Electrical Machines and Power Electronics II	Section A
Thursday	Lab	13:15	15:15	EE lab	EE342 - Electrical Machines and Power Electronics II	Section A
Friday	Lecture	10:20	11:50	Fab Lab 203	EE342 - Electrical Machines and Power Electronics II	Section A
Monday	Lab	15:00	17:00	EE lab	EE442 - Power Electronics	Section A
Wednesday	Lecture	15:00	16:30	Fab Lab 303	EE442 - Power Electronics	Section A
Friday	Lecture	12:15	13:45	Fab Lab 303	EE442 - Power Electronics	Section A
Monday	Lab	11:30	13:30	EE lab	EE454 - Renewable Energy and Smart Grid	Section A
Wednesday	Lecture	13:15	14:45	Fab Lab 303	EE454 - Renewable Energy and Smart Grid	Section A
Friday	Lecture	10:20	11:50	Fab Lab 303	EE454 - Renewable Energy and Smart Grid	Section A
Tuesday	Lecture	15:00	16:30	Databank Foundation Hall 218	ENGL112 - Written and Oral Communication	Section A
Wednesday	Discussion	13:50	14:50	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section A
Thursday	Lecture	15:00	16:30	Databank Foundation Hall 218	ENGL112 - Written and Oral Communication	Section A
Tuesday	Lecture	13:15	14:45	Databank Foundation Hall 218	ENGL112 - Written and Oral Communication	Section B
Wednesday	Discussion	15:00	16:00	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section B
Thursday	Lecture	13:15	14:45	Databank Foundation Hall 218	ENGL112 - Written and Oral Communication	Section B
Tuesday	Lecture	08:00	09:30	Nutor Hall 216	ENGL112 - Written and Oral Communication	Section C
Wednesday	Discussion	16:40	17:40	Nutor Hall 100	ENGL112 - Written and Oral Communication	Section C
Thursday	Lecture	08:00	09:30	Nutor Hall 216	ENGL112 - Written and Oral Communication	Section C
Tuesday	Lecture	13:15	14:45	Apt Hall 216	ENGL112 - Written and Oral Communication	Section D
Wednesday	Discussion	13:50	14:50	Databank Foundation Hall 218	ENGL112 - Written and Oral Communication	Section D
Thursday	Lecture	13:15	14:45	Apt Hall 216	ENGL112 - Written and Oral Communication	Section D
Tuesday	Lecture	15:00	16:30	Apt Hall 216	ENGL112 - Written and Oral Communication	Section E
Wednesday	Discussion	15:00	16:00	Databank Foundation Hall 218	ENGL112 - Written and Oral Communication	Section E
Thursday	Lecture	15:00	16:30	Apt Hall 216	ENGL112 - Written and Oral Communication	Section E
Tuesday	Lecture	11:30	13:00	Radichel MPR	ENGL112 - Written and Oral Communication	Section F
Wednesday	Discussion	15:00	16:00	Norton-Motulsky 207A	ENGL112 - Written and Oral Communication	Section F
Thursday	Lecture	11:30	13:00	Radichel MPR	ENGL112 - Written and Oral Communication	Section F
Tuesday	Lecture	11:30	13:00	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section G
Wednesday	Discussion	13:50	14:50	Norton-Motulsky 207A	ENGL112 - Written and Oral Communication	Section G
Thursday	Lecture	11:30	13:00	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section G
Tuesday	Lecture	13:15	14:45	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section H
Wednesday	Discussion	15:00	16:00	Jackson Lab 221	ENGL112 - Written and Oral Communication	Section H
Thursday	Lecture	13:15	14:45	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section H
Tuesday	Lecture	11:30	13:00	Fab Lab 203	ENGL112 - Written and Oral Communication	Section I
Wednesday	Discussion	16:40	17:40	Fab Lab 303	ENGL112 - Written and Oral Communication	Section I
Thursday	Lecture	11:30	13:00	Fab Lab 203	ENGL112 - Written and Oral Communication	Section I
Tuesday	Lecture	13:15	14:45	Fab Lab 203	ENGL113 - Text and Meaning	Section A
Wednesday	Discussion	13:50	14:50	Nutor Hall 216	ENGL113 - Text and Meaning	Section A
Thursday	Lecture	13:15	14:45	Fab Lab 203	ENGL113 - Text and Meaning	Section A
Tuesday	Lecture	15:00	16:30	Fab Lab 203	ENGL113 - Text and Meaning	Section B
Wednesday	Discussion	15:00	16:00	Nutor Hall 115	ENGL113 - Text and Meaning	Section B
Thursday	Lecture	15:00	16:30	Fab Lab 203	ENGL113 - Text and Meaning	Section B
Monday	Lab	11:30	13:30	Fab Lab 203	ENGR112 - Introduction to Engineering	Section A
Wednesday	Lecture	08:00	09:30	Fab Lab 303	ENGR112 - Introduction to Engineering	Section A
Thursday	Lecture	08:00	09:30	EE lab	ENGR112 - Introduction to Engineering	Section A
Monday	Lab	14:00	16:00	Fab Lab 203	ENGR112 - Introduction to Engineering	Section B
Wednesday	Lecture	09:45	11:15	Fab Lab 303	ENGR112 - Introduction to Engineering	Section B
Thursday	Lecture	09:45	11:15	EE lab	ENGR112 - Introduction to Engineering	Section B
Monday	Lab	08:00	10:00	Fab Lab 303	ENGR312 - Control Systems	Section A
Tuesday	Lecture	09:45	11:15	Fab Lab 303	ENGR312 - Control Systems	Section A
Thursday	Lecture	09:45	11:15	Fab Lab 303	ENGR312 - Control Systems	Section A
Tuesday	Seminar	13:15	14:45	Nutor Hall 100	ENGR401 - Senior Project  & Seminar	Section A
Monday	Lab	15:00	17:00	Fab Lab 303	ENGR411 - Advanced Control Systems	Section A
Tuesday	Lecture	11:30	13:00	Fab Lab 303	ENGR411 - Advanced Control Systems	Section A
Thursday	Lecture	11:30	13:00	Fab Lab 303	ENGR411 - Advanced Control Systems	Section A
Tuesday	Lecture	15:00	16:30	Bio Lab	ENGR412 - Synthetic Biological Engineering	Section A
Wednesday	Lab	11:00	13:00	Bio Lab	ENGR412 - Synthetic Biological Engineering	Section A
Thursday	Lecture	15:00	16:30	Bio Lab	ENGR412 - Synthetic Biological Engineering	Section A
Monday	Lecture	08:00	09:30	Nutor Hall 115	ENGR413 - Project Management and Professional Practice	Section A
Wednesday	Lecture	08:00	09:30	Nutor Hall 115	ENGR413 - Project Management and Professional Practice	Section A
Friday	Lab	12:15	13:45	Norton-Motulsky 207B	ENGR413 - Project Management and Professional Practice	Section A
Monday	Lecture	09:45	11:15	Nutor Hall 115	ENGR413 - Project Management and Professional Practice	Section B
Wednesday	Lecture	09:45	11:15	Nutor Hall 115	ENGR413 - Project Management and Professional Practice	Section B
Friday	Lab	13:55	15:25	Norton-Motulsky 207B	ENGR413 - Project Management and Professional Practice	Section B
Wednesday	Lecture	15:00	16:30	Bio Lab	ENGR442 - Mechatronics	Section A
Thursday	Lecture	09:15	11:15	Bio Lab	ENGR442 - Mechatronics	Section A
Friday	Lab	10:20	11:50	Bio Lab	ENGR442 - Mechatronics	Section A
Monday	Lab	15:00	17:00	Jackson Lab 221	ENGR444 - Automation and Production Systems	Section A
Wednesday	Lecture	15:00	16:30	EE lab	ENGR444 - Automation and Production Systems	Section A
Friday	Lecture	13:55	15:25	Fab Lab 303	ENGR444 - Automation and Production Systems	Section A
Tuesday	Lecture	15:00	16:30	Science Lab	ENGR461 - Financial Engineering	Section A
Wednesday	Discussion	11:30	13:00	Nutor Hall 100	ENGR461 - Financial Engineering	Section A
Thursday	Lecture	15:00	16:30	Science Lab	ENGR461 - Financial Engineering	Section A
Monday	Discussion	16:45	18:15	OT	FRENC122 - Professional French I	Section A
Tuesday	Lecture	13:15	14:45	OT	FRENC122 - Professional French I	Section A
Thursday	Lecture	13:15	14:45	OT	FRENC122 - Professional French I	Section A
Monday	Discussion	16:45	17:45	Norton-Motulsky 207A	FRENC318 - Langue Francaise: La Culture En Plus	Section A
Tuesday	Lecture	08:00	09:30	Norton-Motulsky 207A	FRENC318 - Langue Francaise: La Culture En Plus	Section A
Thursday	Lecture	08:00	09:30	Norton-Motulsky 207A	FRENC318 - Langue Francaise: La Culture En Plus	Section A
Monday	Lecture	11:30	13:00	King Eng. Lab 102	IS333 - IT Infrastructure and System Administration Lab	Section A
Tuesday	Lab	15:00	16:30	Nutor Hall 100	IS333 - IT Infrastructure and System Administration Lab	Section A
Wednesday	Lecture	11:30	13:00	King Eng. Lab 102	IS333 - IT Infrastructure and System Administration Lab	Section A
Monday	Lecture	13:15	14:45	Apt Hall 216	IS362 - IS Project Management	Section A
Wednesday	Lecture	13:15	14:45	Apt Hall 216	IS362 - IS Project Management	Section A
Friday	Lab	13:55	15:25	Radichel MPR	IS362 - IS Project Management	Section A
Monday	Independent Study	16:45	18:15	 - 	IS362 - IS Project Management	Section B
Monday	Discussion	13:45	14:45	Norton-Motulsky 207A	LLB111 - Language for Law	Section A
Wednesday	Lecture	09:45	11:15	Norton-Motulsky 207A	LLB111 - Language for Law	Section A
Monday	Discussion	12:00	13:00	Science Lab	LLB112 - Ghana Legal System & Methods	Section A
Tuesday	Lecture	08:00	09:30	Radichel MPR	LLB112 - Ghana Legal System & Methods	Section A
Thursday	Lecture	08:00	09:30	Radichel MPR	LLB112 - Ghana Legal System & Methods	Section A
Monday	Lecture	15:00	16:30	Apt Hall 216	LLB114 - Legal Writing	Section A
Wednesday	Discussion	15:00	16:00	Apt Hall 216	LLB114 - Legal Writing	Section A
Monday	Lecture	08:00	09:30	Radichel MPR	LLB150 - Introduction to Public Policy	Section A
Wednesday	Lecture	08:00	09:30	Radichel MPR	LLB150 - Introduction to Public Policy	Section A
Tuesday	Period	15:00	16:30	Jackson Lab 221	LLB213 - Constitutional Law I	Section A
Thursday	Lecture	15:00	16:30	Jackson Lab 221	LLB213 - Constitutional Law I	Section A
Friday	Discussion	09:10	10:10	Nutor Hall 100	LLB213 - Constitutional Law I	Section A
Tuesday	Lecture	09:45	11:15	Norton-Motulsky 207A	LLB215 - Contract Law I	Section A
Thursday	Lecture	09:45	11:15	Norton-Motulsky 207A	LLB215 - Contract Law I	Section A
Tuesday	Lecture	08:00	09:30	Nutor Hall 115	MATH 212 - Linear Algebra	Section A
Thursday	Lecture	08:00	09:30	Nutor Hall 115	MATH 212 - Linear Algebra	Section A
Friday	Discussion	08:40	10:10	Apt Hall 217	MATH 212 - Linear Algebra	Section A
Tuesday	Lecture	09:45	11:15	Nutor Hall 115	MATH 212 - Linear Algebra	Section B
Thursday	Lecture	09:45	11:15	Nutor Hall 115	MATH 212 - Linear Algebra	Section B
Friday	Lab	10:20	11:50	Apt Hall 217	MATH 212 - Linear Algebra	Section B
Monday	Lecture	08:00	09:30	Jackson Lab 222	MATH101 - College Algebra	Section A
Tuesday	Lecture	08:00	09:30	Jackson Lab 222	MATH101 - College Algebra	Section A
Thursday	Lecture	08:00	09:30	Jackson Lab 222	MATH101 - College Algebra	Section A
Friday	Discussion	10:20	11:50	Radichel MPR	MATH101 - College Algebra	Section A
Monday	Lecture	08:00	09:30	Jackson Hall 115	MATH121 - Pre-Calculus I	Section A
Tuesday	Lecture	08:00	09:30	Jackson Hall 115	MATH121 - Pre-Calculus I	Section A
Wednesday	Lecture	08:00	09:30	Jackson Hall 115	MATH121 - Pre-Calculus I	Section A
Friday	Discussion	10:20	11:50	Jackson Hall 115	MATH121 - Pre-Calculus I	Section A
Monday	Lecture	09:45	11:15	Jackson Hall 115	MATH121 - Pre-Calculus I	Section B
Tuesday	Discussion	09:45	11:15	Jackson Hall 115	MATH121 - Pre-Calculus I	Section B
Wednesday	Lecture	09:45	11:15	Jackson Hall 115	MATH121 - Pre-Calculus I	Section B
Friday	Lecture	12:15	13:45	Jackson Hall 115	MATH121 - Pre-Calculus I	Section B
Monday	Lecture	09:45	11:15	Radichel MPR	MATH122 - Pre-Calculus II	Section A
Tuesday	Lecture	09:45	11:15	Radichel MPR	MATH122 - Pre-Calculus II	Section A
Thursday	Lecture	09:45	11:15	Radichel MPR	MATH122 - Pre-Calculus II	Section A
Friday	Discussion	12:15	13:45	Radichel MPR	MATH122 - Pre-Calculus II	Section A
Monday	Lecture	08:00	09:30	Jackson Hall 116	MATH141 - Calculus I	Section A
Tuesday	Lecture	08:00	09:30	Jackson Hall 116	MATH141 - Calculus I	Section A
Thursday	Lecture	08:00	09:30	Jackson Hall 115	MATH141 - Calculus I	Section A
Friday	Discussion	10:20	11:50	Jackson Hall 116	MATH141 - Calculus I	Section A
Monday	Lecture	09:45	11:15	Jackson Hall 116	MATH141 - Calculus I	Section B
Tuesday	Lecture	09:45	11:15	Jackson Hall 116	MATH141 - Calculus I	Section B
Wednesday	Lecture	09:45	11:15	Jackson Hall 116	MATH141 - Calculus I	Section B
Friday	Discussion	12:15	13:45	Jackson Hall 116	MATH141 - Calculus I	Section B
Monday	Lecture	11:30	13:00	Jackson Hall 116	MATH141 - Calculus I	Section C
Tuesday	Lecture	11:30	13:00	Jackson Hall 116	MATH141 - Calculus I	Section C
Wednesday	Lecture	11:30	13:00	Jackson Hall 116	MATH141 - Calculus I	Section C
Friday	Discussion	13:55	15:25	Jackson Hall 116	MATH141 - Calculus I	Section C
Monday	Discussion	16:45	18:15	Nutor Hall 100	MATH146 - Applied Calculus - Part II	Section A
Tuesday	Lecture	11:30	13:00	Nutor Hall 100	MATH146 - Applied Calculus - Part II	Section A
Thursday	Lecture	11:30	13:00	Nutor Hall 100	MATH146 - Applied Calculus - Part II	Section A
Monday	Lecture	08:00	09:30	Norton-Motulsky 207A	MATH161 - Engineering Calculus	Section A
Tuesday	Lecture	08:00	09:30	EE lab	MATH161 - Engineering Calculus	Section A
Wednesday	Lecture	08:00	09:30	Norton-Motulsky 207A	MATH161 - Engineering Calculus	Section A
Monday	Lecture	09:45	11:15	Norton-Motulsky 207A	MATH161 - Engineering Calculus	Section B
Tuesday	Lecture	09:45	11:15	EE lab	MATH161 - Engineering Calculus	Section B
Wednesday	Lecture	11:30	13:00	Science Lab	MATH161 - Engineering Calculus	Section B
Tuesday	Lecture	08:00	09:30	Databank Foundation Hall 218	MATH223 - Quantitative Methods	Section A
Thursday	Lecture	08:00	09:30	Databank Foundation Hall 218	MATH223 - Quantitative Methods	Section A
Friday	Discussion	10:20	11:50	Nutor Hall 115	MATH223 - Quantitative Methods	Section A
Tuesday	Lecture	09:45	11:15	Databank Foundation Hall 218	MATH223 - Quantitative Methods	Section B
Thursday	Lecture	09:45	11:15	Databank Foundation Hall 218	MATH223 - Quantitative Methods	Section B
Friday	Discussion	12:15	13:45	Nutor Hall 115	MATH223 - Quantitative Methods	Section B
Tuesday	Lecture	11:30	13:00	Databank Foundation Hall 218	MATH223 - Quantitative Methods	Section C
Thursday	Lecture	11:30	13:00	Databank Foundation Hall 218	MATH223 - Quantitative Methods	Section C
Friday	Discussion	13:55	15:25	Nutor Hall 115	MATH223 - Quantitative Methods	Section C
Monday	Discussion	13:15	14:45	Databank Foundation Hall 218	MATH251 - Differential Equations and Numerical Methods	Section A
Tuesday	Lecture	08:00	09:30	Science Lab	MATH251 - Differential Equations and Numerical Methods	Section A
Thursday	Lecture	08:00	09:30	Science Lab	MATH251 - Differential Equations and Numerical Methods	Section A
Monday	Discussion	15:00	16:30	Databank Foundation Hall 218	MATH251 - Differential Equations and Numerical Methods	Section B
Tuesday	Lecture	09:45	11:15	Science Lab	MATH251 - Differential Equations and Numerical Methods	Section B
Thursday	Lecture	09:45	11:15	Science Lab	MATH251 - Differential Equations and Numerical Methods	Section B
Monday	Lab	10:10	12:10	Fab Lab 303	ME301 - Mechanical Machine Design	Section A
Tuesday	Lecture	08:00	09:30	Fab Lab 303	ME301 - Mechanical Machine Design	Section A
Thursday	Lecture	08:00	09:30	Fab Lab 303	ME301 - Mechanical Machine Design	Section A
Monday	Lab	15:00	17:00	King Eng. Lab 102	ME412 - Advanced Thermodynamics	Section A
Wednesday	Lecture	08:00	09:30	Bio Lab	ME412 - Advanced Thermodynamics	Section A
Friday	Lecture	13:55	15:25	Bio Lab	ME412 - Advanced Thermodynamics	Section A
Tuesday	Lecture	15:00	16:30	ME Lab	ME431 - Fluid Mechanics	Section A
Wednesday	Lab	15:00	17:00	ME Lab	ME431 - Fluid Mechanics	Section A
Thursday	Lecture	15:00	16:30	ME Lab	ME431 - Fluid Mechanics	Section A
Monday	Lab	11:30	13:30	Norton-Motulsky 207A	ME432 - Computational Fluid Dynamics	Section A
Wednesday	Lecture	13:15	14:45	Bio Lab	ME432 - Computational Fluid Dynamics	Section A
Friday	Lecture	12:15	13:45	Bio Lab	ME432 - Computational Fluid Dynamics	Section A
Wednesday	Lecture	11:30	13:30	ME Lab	ME441 - Manufacturing Processes	Section A
Friday	Lab	08:50	11:50	ME Lab	ME441 - Manufacturing Processes	Section A
Monday	Lab	15:00	17:00	ME Lab	ME445 - Machine Shop and Factory Design	Section A
Wednesday	Lecture	09:45	11:15	ME Lab	ME445 - Machine Shop and Factory Design	Section A
Friday	Lecture	12:15	13:45	ME Lab	ME445 - Machine Shop and Factory Design	Section A
Monday	Discussion	15:00	16:00	Jackson Lab 222	POLS221 - African Philosophical Thought	Section A
Tuesday	Lecture	15:00	16:30	Jackson Hall 115	POLS221 - African Philosophical Thought	Section A
Thursday	Lecture	15:00	16:30	Jackson Hall 115	POLS221 - African Philosophical Thought	Section A
Monday	Lecture	13:15	14:45	Norton-Motulsky 207B	POLS222 - Political Economy of Healthcare in Ghana	Section A
Wednesday	Lecture	13:15	14:45	Norton-Motulsky 207B	POLS222 - Political Economy of Healthcare in Ghana	Section A
Friday	Discussion	08:00	09:00	Jackson Lab 222	POLS222 - Political Economy of Healthcare in Ghana	Section A
Monday	Lecture	08:00	09:30	Science Lab	SC221 - Materials Science & Chemistry	Section A
Wednesday	Lecture	08:00	09:30	Science Lab	SC221 - Materials Science & Chemistry	Section A
Friday	Lab	09:50	11:50	Science Lab	SC221 - Materials Science & Chemistry	Section A
Monday	Lecture	09:45	11:15	Science Lab	SC221 - Materials Science & Chemistry	Section B
Wednesday	Lecture	09:45	11:15	Science Lab	SC221 - Materials Science & Chemistry	Section B
Friday	Lab	12:15	14:15	Science Lab	SC221 - Materials Science & Chemistry	Section B
Tuesday	Lecture	13:15	14:45	Jackson Hall 116	SOAN 322 - African Cultural Institutions	Section A
Thursday	Lecture	13:15	14:45	Jackson Hall 116	SOAN 322 - African Cultural Institutions	Section A
Friday	Discussion	09:10	10:10	Jackson Lab 221	SOAN 322 - African Cultural Institutions	Section A
Friday	Independent Study	15:30	17:00	 - 	SOAN111 - Leadership Seminar I: What Makes a Good Leader?	Section A
Tuesday	Lecture	11:30	13:00	Science Lab	SOAN225 - Ghanaian Popular Culture	Section A
Thursday	Lecture	11:30	13:00	Science Lab	SOAN225 - Ghanaian Popular Culture	Section A
Friday	Discussion	08:00	09:00	Science Lab	SOAN225 - Ghanaian Popular Culture	Section A
Tuesday	Lecture	11:30	13:00	EE lab	SOAN236 - ESG: Corporate Ethics in Africa	Section A
Thursday	Lecture	11:30	13:00	EE lab	SOAN236 - ESG: Corporate Ethics in Africa	Section A
Friday	Discussion	09:10	10:10	Jackson Hall 115	SOAN236 - ESG: Corporate Ethics in Africa	Section A
Tuesday	Lecture	09:45	11:15	Jackson Lab 222	SOAN239 - African & Diasporan Choir	Section A
Thursday	Lecture	09:45	11:15	Jackson Lab 222	SOAN239 - African & Diasporan Choir	Section A
Friday	Discussion	08:00	09:00	Nutor Hall 100	SOAN239 - African & Diasporan Choir	Section A
Monday	Discussion	13:45	14:45	King Eng. Lab 102	SOAN242 - Modern Dance Traditions of Ghana	Section A
Tuesday	Lecture	09:45	11:15	King Eng. Lab 102	SOAN242 - Modern Dance Traditions of Ghana	Section A
Thursday	Lecture	09:45	11:15	King Eng. Lab 102	SOAN242 - Modern Dance Traditions of Ghana	Section A
Monday	Lecture	15:00	16:30	Norton-Motulsky 207B	SOAN251 - Africa in the International Setting	Section A
Wednesday	Lecture	15:00	16:30	Norton-Motulsky 207B	SOAN251 - Africa in the International Setting	Section A
Friday	Discussion	09:10	10:10	Jackson Lab 222	SOAN251 - Africa in the International Setting	Section A
Tuesday	Lecture	15:00	16:30	Jackson Hall 116	SOAN301 - Introduction to Africana Studies: The Global Black Experience	Section A
Thursday	Lecture	15:00	16:30	Jackson Hall 116	SOAN301 - Introduction to Africana Studies: The Global Black Experience	Section A
Friday	Discussion	08:00	09:00	Jackson Lab 221	SOAN301 - Introduction to Africana Studies: The Global Black Experience	Section A
Tuesday	Seminar	08:00	09:30	Nutor Hall 100	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section A
Wednesday	Seminar	12:00	13:00	EE lab	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section A
Tuesday	Seminar	09:45	11:15	Nutor Hall 100	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section B
Wednesday	Seminar	15:00	16:00	Apt Hall 217	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section B
Tuesday	Seminar	08:00	09:30	Norton-Motulsky 207B	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section C
Thursday	Seminar	08:30	09:30	Nutor Hall 100	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section C
Monday	Seminar	13:15	14:45	Fab Lab 303	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section D
Wednesday	Seminar	16:40	17:40	Nutor Hall 115	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section D
Monday	Seminar	13:15	14:45	Apt Hall 217	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section E
Wednesday	Seminar	13:50	14:50	Apt Hall 217	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section E
Monday	Seminar	15:00	16:30	Apt Hall 217	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section F
Wednesday	Discussion	16:40	17:40	Apt Hall 216	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section F
Tuesday	Seminar	09:45	11:15	Fab Lab 203	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section G
Thursday	Seminar	09:45	10:45	Nutor Hall 100	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section G
Tuesday	Seminar	08:00	09:30	Jackson Lab 221	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section H
Thursday	Discussion	08:30	09:30	Jackson Lab 221	SOAN311 - Leadership Seminar III: The Economic Organization of a Good Society	Section H
Monday	Discussion	08:30	09:30	Fab Lab 203	SOAN325 - Research Methods	Section A
Tuesday	Lecture	08:00	09:30	Apt Hall 216	SOAN325 - Research Methods	Section A
Thursday	Lecture	08:00	09:30	Apt Hall 216	SOAN325 - Research Methods	Section A
Monday	Discussion	09:45	10:45	Fab Lab 203	SOAN325 - Research Methods	Section B
Tuesday	Lecture	09:45	11:15	Apt Hall 216	SOAN325 - Research Methods	Section B
Thursday	Lecture	09:45	11:15	Apt Hall 216	SOAN325 - Research Methods	Section B
Monday	Lecture	08:00	09:30	Nutor Hall 100	SOAN325 - Research Methods	Section C
Wednesday	Lecture	08:00	09:30	Nutor Hall 100	SOAN325 - Research Methods	Section C
Thursday	Discussion	08:30	09:30	Jackson Hall 116	SOAN325 - Research Methods	Section C
Monday	Lecture	09:45	11:15	Norton-Motulsky 207B	SOAN325 - Research Methods	Section D
Wednesday	Lecture	09:45	11:15	Radichel MPR	SOAN325 - Research Methods	Section D
Thursday	Discussion	09:45	10:45	Jackson Hall 116	SOAN325 - Research Methods	Section D
Monday	Lecture	11:30	13:00	Norton-Motulsky 207B	SOAN325 - Research Methods	Section E
Wednesday	Lecture	11:30	13:00	Norton-Motulsky 207A	SOAN325 - Research Methods	Section E
Thursday	Discussion	11:30	12:30	Jackson Hall 116	SOAN325 - Research Methods	Section E
Tuesday	Class Meeting	16:45	18:15	Apt Hall 216	SOAN328 - Creative and Research Internship	Section A
Thursday	Set up for grading	16:45	18:15	OT	SOAN329 - Creative and Research Internship II	Section A
Tuesday	Lecture	11:30	13:00	Bio Lab	SOAN332 - Sustainability and Systems Thinking	Section A
Thursday	Lecture	11:30	13:00	Bio Lab	SOAN332 - Sustainability and Systems Thinking	Section A
Friday	Discussion	09:10	10:10	Fab Lab 303	SOAN332 - Sustainability and Systems Thinking	Section A
Tuesday	Seminar	13:15	14:45	Radichel MPR	SOAN411 - Leadership Seminar IV: Leadership as Service	Section A
Thursday	Seminar	13:15	14:45	Radichel MPR	SOAN411 - Leadership Seminar IV: Leadership as Service	Section A
Tuesday	Seminar	15:00	16:30	Radichel MPR	SOAN411 - Leadership Seminar IV: Leadership as Service	Section B
Thursday	Lecture	15:00	16:30	Radichel MPR	SOAN411 - Leadership Seminar IV: Leadership as Service	Section B
Monday	Seminar	13:15	14:45	Science Lab	SOAN411 - Leadership Seminar IV: Leadership as Service	Section C
Wednesday	Seminar	13:15	14:45	Science Lab	SOAN411 - Leadership Seminar IV: Leadership as Service	Section C
Monday	Seminar	15:00	16:30	Science Lab	SOAN411 - Leadership Seminar IV: Leadership as Service	Section D
Wednesday	Seminar	15:00	16:30	Science Lab	SOAN411 - Leadership Seminar IV: Leadership as Service	Section D
