-- This file was generated by update.py on 2025-11-03 13:25:55
DELETE FROM public.timetable;

COPY public.timetable (day, period_name, start_time, end_time, location, course_code, section) FROM stdin;
Monday	Lab	15:00	17:00	Bio Lab	BENG181 - Molecular and Cell Biology	Section A
Wednesday	Lecture	08:00	09:30	Bio Lab	BENG181 - Molecular and Cell Biology	Section A
Thursday	Lecture	08:00	09:30	Bio Lab	BENG181 - Molecular and Cell Biology	Section A
Monday	Lecture	08:00	09:30	Bio Lab	BENG281 - General Chemistry	Section A
Tuesday	Lecture	08:00	09:30	Bio Lab	BENG281 - General Chemistry	Section A
Friday	Lab	08:00	10:00	Bio Lab	BENG281 - General Chemistry	Section A
Tuesday	Lecture	13:15	14:45	Apt Hall 216	BUSA 432 - Organisational Development	Section A
Thursday	Lecture	13:15	14:45	Apt Hall 216	BUSA 432 - Organisational Development	Section A
Friday	Discussion	09:10	10:10	EE lab	BUSA 432 - Organisational Development	Section A
Tuesday	Lecture	09:45	11:15	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section A
Thursday	Lecture	09:45	11:15	Norton-Motulsky 207A	BUSA161 - Foundations of Design and Entrepreneurship I	Section A
Friday	Discussion	08:00	09:00	Nutor Hall 115	BUSA161 - Foundations of Design and Entrepreneurship I	Section A
Tuesday	Lecture	11:30	13:00	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section B
Thursday	Lecture	11:30	13:00	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section B
Friday	Discussion	09:10	10:10	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section B
Tuesday	Lecture	13:15	14:45	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section C
Thursday	Lecture	13:15	14:45	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section C
Friday	Discussion	08:00	09:00	Norton-Motulsky 207B	BUSA161 - Foundations of Design and Entrepreneurship I	Section C
Tuesday	Lecture	09:45	11:15	Nutor Hall 100	BUSA161 - Foundations of Design and Entrepreneurship I	Section D
Thursday	Lecture	09:45	11:15	Nutor Hall 100	BUSA161 - Foundations of Design and Entrepreneurship I	Section D
Friday	Discussion	08:00	09:00	Nutor Hall 100	BUSA161 - Foundations of Design and Entrepreneurship I	Section D
Tuesday	Lecture	11:30	13:00	Nutor Hall 100	BUSA161 - Foundations of Design and Entrepreneurship I	Section E
Thursday	Lecture	11:30	13:00	Nutor Hall 100	BUSA161 - Foundations of Design and Entrepreneurship I	Section E
Friday	Discussion	09:10	10:10	Nutor Hall 100	BUSA161 - Foundations of Design and Entrepreneurship I	Section E
Tuesday	Lecture	13:15	14:45	Nutor Hall 100	BUSA161 - Foundations of Design and Entrepreneurship I	Section F
Thursday	Lecture	13:15	14:45	Nutor Hall 100	BUSA161 - Foundations of Design and Entrepreneurship I	Section F
Friday	Discussion	09:10	10:10	Nutor Hall 115	BUSA161 - Foundations of Design and Entrepreneurship I	Section F
Monday	Lecture	08:00	09:30	Jackson Lab 222	BUSA210 - Financial Accounting	Section A
Wednesday	Lecture	08:00	09:30	Jackson Lab 222	BUSA210 - Financial Accounting	Section A
Thursday	Discussion	08:30	09:30	Jackson Hall 116	BUSA210 - Financial Accounting	Section A
Monday	Lecture	09:45	11:15	Apt Hall 216	BUSA210 - Financial Accounting	Section B
Wednesday	Lecture	09:45	11:15	Apt Hall 216	BUSA210 - Financial Accounting	Section B
Thursday	Discussion	09:45	10:45	Jackson Hall 116	BUSA210 - Financial Accounting	Section B
Monday	Lecture	09:45	11:15	Jackson Hall 115	BUSA224 - Finance for Non-finance Managers	Section A
Wednesday	Lecture	09:45	11:15	Jackson Hall 115	BUSA224 - Finance for Non-finance Managers	Section A
Friday	Discussion	08:00	09:00	Jackson Hall 116	BUSA224 - Finance for Non-finance Managers	Section A
Monday	Lecture	11:30	13:00	Nutor Hall 115	BUSA224 - Finance for Non-finance Managers	Section B
Wednesday	Lecture	11:30	13:00	Nutor Hall 115	BUSA224 - Finance for Non-finance Managers	Section B
Friday	Discussion	09:10	10:10	Jackson Hall 116	BUSA224 - Finance for Non-finance Managers	Section B
Monday	Lecture	11:30	13:00	Jackson Lab 222	BUSA224 - Finance for Non-finance Managers	Section C
Wednesday	Lecture	11:30	13:00	Jackson Lab 222	BUSA224 - Finance for Non-finance Managers	Section C
Friday	Discussion	13:55	14:55	Radichel MPR	BUSA224 - Finance for Non-finance Managers	Section C
Tuesday	Lecture	08:00	09:30	Nutor Hall 100	BUSA304 - Operations Management	Section A
Thursday	Lecture	08:00	09:30	Nutor Hall 100	BUSA304 - Operations Management	Section A
Friday	Discussion	10:20	11:20	Nutor Hall 115	BUSA304 - Operations Management	Section A
Monday	Discussion	13:50	14:50	Norton-Motulsky 207A	BUSA304 - Operations Management	Section B
Tuesday	Lecture	11:30	13:00	Nutor Hall 115	BUSA304 - Operations Management	Section B
Thursday	Lecture	11:30	13:00	Nutor Hall 115	BUSA304 - Operations Management	Section B
Tuesday	Lecture	13:15	14:45	Fab Lab 203	BUSA304 - Operations Management	Section C
Thursday	Lecture	13:15	14:45	Fab Lab 203	BUSA304 - Operations Management	Section C
Friday	Discussion	12:15	13:15	Nutor Hall 115	BUSA304 - Operations Management	Section C
Friday	Independent Study	15:30	17:00	 - 	BUSA311 - Managerial Accounting	Section A
Monday	Lecture	08:00	09:30	Apt Hall 216	BUSA321 - Investments	Section A
Wednesday	Lecture	08:00	09:30	Apt Hall 216	BUSA321 - Investments	Section A
Thursday	Discussion	15:30	16:30	Norton-Motulsky 207B	BUSA321 - Investments	Section A
Monday	Lecture	09:45	11:15	Nutor Hall 115	BUSA321 - Investments	Section B
Wednesday	Lecture	09:45	11:15	Nutor Hall 115	BUSA321 - Investments	Section B
Thursday	Discussion	16:40	17:40	Norton-Motulsky 207B	BUSA321 - Investments	Section B
Monday	Lecture	08:00	09:30	Nutor Hall 115	BUSA323 - Corporate Finance	Section A
Tuesday	Discussion	15:30	16:30	Norton-Motulsky 207B	BUSA323 - Corporate Finance	Section A
Wednesday	Lecture	08:00	09:30	Nutor Hall 115	BUSA323 - Corporate Finance	Section A
Monday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA323 - Corporate Finance	Section B
Tuesday	Discussion	16:40	17:40	Norton-Motulsky 207B	BUSA323 - Corporate Finance	Section B
Wednesday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA323 - Corporate Finance	Section B
Monday	Lecture	11:30	13:00	Norton-Motulsky 207B	BUSA323 - Corporate Finance	Section C
Wednesday	Lecture	11:30	13:00	Norton-Motulsky 207B	BUSA323 - Corporate Finance	Section C
Thursday	Discussion	08:30	09:30	Science Lab	BUSA323 - Corporate Finance	Section C
Friday	Independent Study	15:30	17:00	 - 	BUSA341 - Marketing	Section A
Monday	Lecture	11:30	13:00	Nutor Hall 100	BUSA350 - International Trade and Policy	Section A
Wednesday	Lecture	11:30	13:00	Nutor Hall 100	BUSA350 - International Trade and Policy	Section A
Friday	Discussion	12:15	13:15	Nutor Hall 100	BUSA350 - International Trade and Policy	Section A
Monday	Lecture	08:00	09:30	Norton-Motulsky 207B	BUSA350 - International Trade and Policy	Section B
Wednesday	Lecture	08:00	09:30	Norton-Motulsky 207B	BUSA350 - International Trade and Policy	Section B
Friday	Discussion	10:20	11:20	Nutor Hall 100	BUSA350 - International Trade and Policy	Section B
Monday	Discussion	11:30	13:00	Apt Hall 216	BUSA401_A - Entrepreneurship I	Section A
Wednesday	Lecture	11:30	14:45	Apt Hall 216	BUSA401_A - Entrepreneurship I	Section A
Tuesday	Lecture	08:00	09:30	Norton-Motulsky 207A	BUSA403 - Company and Commercial Law	Section A
Wednesday	Discussion	09:45	10:45	King Eng. Lab 102	BUSA403 - Company and Commercial Law	Section A
Thursday	Lecture	08:00	09:30	Norton-Motulsky 207A	BUSA403 - Company and Commercial Law	Section A
Tuesday	Lecture	08:00	09:30	Norton-Motulsky 207B	BUSA405 - Competitive Strategy	Section A
Thursday	Lecture	08:00	09:30	Norton-Motulsky 207B	BUSA405 - Competitive Strategy	Section A
Friday	Discussion	10:20	11:20	Norton-Motulsky 207B	BUSA405 - Competitive Strategy	Section A
Tuesday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA405 - Competitive Strategy	Section B
Thursday	Lecture	09:45	11:15	Norton-Motulsky 207B	BUSA405 - Competitive Strategy	Section B
Friday	Discussion	12:15	13:15	Norton-Motulsky 207B	BUSA405 - Competitive Strategy	Section B
Monday	Seminar	13:15	14:45	King Eng. Lab 102	BUSA411 - Applied Project I (BA)	Section A
Wednesday	Seminar	13:15	14:45	King Eng. Lab 102	BUSA411 - Applied Project I (BA)	Section A
Monday	Lecture	15:00	16:30	Apt Hall 216	BUSA423 - International Finance	Section A
Wednesday	Lecture	15:00	16:30	Apt Hall 216	BUSA423 - International Finance	Section A
Thursday	Discussion	12:00	13:00	EE lab	BUSA423 - International Finance	Section A
Tuesday	Lecture	15:00	16:30	Nutor Hall 100	BUSA431 - Real Estate Development	Section A
Thursday	Lecture	15:00	16:30	Nutor Hall 100	BUSA431 - Real Estate Development	Section A
Friday	Discussion	08:00	09:00	Apt Hall 216	BUSA431 - Real Estate Development	Section A
Monday	Lecture	16:45	19:15	Radichel MPR	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Tuesday	Lecture	16:45	19:15	Radichel MPR	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Wednesday	Lecture	16:45	19:15	Radichel MPR	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Thursday	Lecture	16:45	19:15	Radichel MPR	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Friday	Discussion	09:10	10:10	Apt Hall 216	BUSA433 - AI in Business: Empowering Tomorrow's Leaders	Section A
Tuesday	Lecture	11:30	13:00	Nutor Hall 216	BUSA435 - International Human Resource Management	Section A
Thursday	Lecture	11:30	13:00	Nutor Hall 216	BUSA435 - International Human Resource Management	Section A
Friday	Discussion	08:00	09:00	King Eng. Lab 102	BUSA435 - International Human Resource Management	Section A
Monday	Lecture	15:00	16:30	Nutor Hall 100	BUSA442 - Strategic Brand Management	Section A
Wednesday	Lecture	15:00	16:30	Nutor Hall 100	BUSA442 - Strategic Brand Management	Section A
Friday	Discussion	13:55	14:55	Nutor Hall 100	BUSA442 - Strategic Brand Management	Section A
Tuesday	Lecture	09:45	11:15	Science Lab	BUSA444 - Supply Chain Management	Section A
Thursday	Lecture	09:45	11:15	Jackson Lab 222	BUSA444 - Supply Chain Management	Section A
Friday	Discussion	09:10	10:10	Jackson Lab 221	BUSA444 - Supply Chain Management	Section A
Monday	Seminar	13:15	14:45	Nutor Hall 115	BUSA491 - Undergraduate Thesis I (BA)	Section A
Wednesday	Seminar	13:15	14:45	Nutor Hall 100	BUSA491 - Undergraduate Thesis I (BA)	Section A
Friday	Independent Study	15:30	17:00	 - 	BUSA492 - Undergraduate Thesis II (BA)	Section A
Monday	Lab	10:10	12:10	Fab Lab 203	CE451 - Embedded Systems	Section A
Tuesday	Lecture	08:00	09:30	Fab Lab 203	CE451 - Embedded Systems	Section A
Thursday	Lecture	08:00	09:30	Fab Lab 203	CE451 - Embedded Systems	Section A
Tuesday	Lecture	13:15	14:45	Jackson Lab 221	CS 452 - Machine Learning	Section A
Thursday	Lecture	13:15	14:45	Jackson Lab 221	CS 452 - Machine Learning	Section A
Friday	Lab	12:15	13:45	Apt Hall 216	CS 452 - Machine Learning	Section A
Monday	Lecture	08:00	09:30	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section A
Wednesday	Lecture	08:00	09:30	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section A
Friday	Lab	10:20	11:50	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section A
Monday	Lecture	11:30	13:00	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section B
Wednesday	Lecture	11:30	13:00	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section B
Friday	Lab	13:55	15:25	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section B
Monday	Lecture	13:15	14:45	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section C
Wednesday	Lecture	13:15	14:45	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section C
Friday	Lab	12:15	13:45	Jackson Hall 115	CS111 - Introduction to Computing and Information Systems	Section C
Tuesday	Lecture	09:45	11:15	EE lab	CS212 - Computer Programming for CS	Section A
Thursday	Lecture	09:45	11:15	EE lab	CS212 - Computer Programming for CS	Section A
Friday	Lab	10:20	11:50	Jackson Hall 116	CS212 - Computer Programming for CS	Section A
Tuesday	Lecture	08:00	09:30	Apt Hall 217	CS213 - Object-Oriented Programming	Section A
Thursday	Lecture	08:00	09:30	Apt Hall 217	CS213 - Object-Oriented Programming	Section A
Friday	Lab	10:20	11:50	Apt Hall 217	CS213 - Object-Oriented Programming	Section A
Tuesday	Lecture	09:45	11:15	Apt Hall 217	CS213 - Object-Oriented Programming	Section B
Thursday	Lecture	09:45	11:15	Apt Hall 217	CS213 - Object-Oriented Programming	Section B
Friday	Lab	12:15	13:45	Apt Hall 217	CS213 - Object-Oriented Programming	Section B
Tuesday	Lecture	11:30	13:00	Apt Hall 217	CS213 - Object-Oriented Programming	Section C
Thursday	Lecture	11:30	13:00	Apt Hall 217	CS213 - Object-Oriented Programming	Section C
Friday	Lab	13:55	15:25	Apt Hall 217	CS213 - Object-Oriented Programming	Section C
Monday	Lecture	08:00	09:30	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section A
Wednesday	Lecture	08:00	09:30	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section A
Friday	Discussion	10:20	11:50	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section A
Monday	Lecture	09:45	11:15	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section B
Wednesday	Lecture	09:45	11:15	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section B
Friday	Discussion	12:15	13:45	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section B
Monday	Lecture	11:30	13:00	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section C
Wednesday	Lecture	11:30	13:00	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section C
Friday	Discussion	13:55	15:25	Databank Foundation Hall 218	CS221 - Discrete Structures and Theory	Section C
Friday	Independent Study	15:30	17:00	 - 	CS222 - Data Structures and Algorithms	Section A
Monday	Lecture	13:15	14:45	Nutor Hall 216	CS313 - Intermediate Computer Programming	Section A
Wednesday	Lecture	13:15	14:45	Nutor Hall 216	CS313 - Intermediate Computer Programming	Section A
Thursday	Lab	08:00	09:30	Nutor Hall 216	CS313 - Intermediate Computer Programming	Section A
Monday	Lecture	15:00	16:30	Nutor Hall 216	CS313 - Intermediate Computer Programming	Section B
Wednesday	Lecture	15:00	16:30	Nutor Hall 216	CS313 - Intermediate Computer Programming	Section B
Thursday	Lab	09:45	11:15	Nutor Hall 216	CS313 - Intermediate Computer Programming	Section B
Tuesday	Lecture	08:00	09:30	Nutor Hall 115	CS330 - Hardware and Systems Fundamentals	Section A
Thursday	Lab	08:00	09:30	Nutor Hall 115	CS330 - Hardware and Systems Fundamentals	Section A
Tuesday	Lecture	09:45	11:15	Nutor Hall 115	CS330 - Hardware and Systems Fundamentals	Section B
Thursday	Lab	09:45	11:15	Nutor Hall 115	CS330 - Hardware and Systems Fundamentals	Section B
Tuesday	Lecture	13:15	14:45	Science Lab	CS331 - Computer Organization and Architecture	Section A
Thursday	Lecture	13:15	14:45	Science Lab	CS331 - Computer Organization and Architecture	Section A
Friday	Lab	12:15	13:45	Science Lab	CS331 - Computer Organization and Architecture	Section A
Monday	Lecture	08:00	09:30	Jackson Lab 221	CS341 - Web Technologies	Section A
Wednesday	Lecture	08:00	09:30	Jackson Lab 221	CS341 - Web Technologies	Section A
Friday	Lab	10:20	11:50	Jackson Lab 221	CS341 - Web Technologies	Section A
Monday	Lecture	09:45	11:15	Jackson Lab 221	CS341 - Web Technologies	Section B
Wednesday	Lecture	09:45	11:15	Jackson Lab 221	CS341 - Web Technologies	Section B
Friday	Lab	12:15	13:45	Jackson Lab 221	CS341 - Web Technologies	Section B
Monday	Lecture	11:30	13:00	Jackson Lab 221	CS341 - Web Technologies	Section C
Wednesday	Lecture	11:30	13:00	Jackson Lab 221	CS341 - Web Technologies	Section C
Friday	Lab	13:55	15:25	Jackson Lab 221	CS341 - Web Technologies	Section C
Monday	Seminar	13:15	14:45	Nutor Hall 100	CS410-SEM - CSIS Capstone Seminar	Section A
Tuesday	Lecture	13:15	14:45	King Eng. Lab 102	CS424 - Advanced Database Systems	Section A
Thursday	Lecture	13:15	14:45	King Eng. Lab 102	CS424 - Advanced Database Systems	Section A
Friday	Lab	10:20	11:50	King Eng. Lab 102	CS424 - Advanced Database Systems	Section A
Tuesday	Lecture	08:00	09:30	Apt Hall 216	CS433 - Operating Systems / Operating Systems and Systems Administration	Section A
Thursday	Lecture	08:00	09:30	Apt Hall 216	CS433 - Operating Systems / Operating Systems and Systems Administration	Section A
Friday	Lab	13:55	15:25	Apt Hall 216	CS433 - Operating Systems / Operating Systems and Systems Administration	Section A
Tuesday	Lecture	09:45	11:15	Apt Hall 216	CS433 - Operating Systems / Operating Systems and Systems Administration	Section B
Thursday	Lecture	09:45	11:15	Apt Hall 216	CS433 - Operating Systems / Operating Systems and Systems Administration	Section B
Friday	Lab	10:20	11:50	Apt Hall 216	CS433 - Operating Systems / Operating Systems and Systems Administration	Section B
Monday	Lecture	15:00	16:30	Jackson Lab 221	CS442 - E-Commerce	Section A
Wednesday	Lecture	15:00	16:30	Jackson Lab 221	CS442 - E-Commerce	Section A
Thursday	Lab	09:45	11:15	Jackson Lab 221	CS442 - E-Commerce	Section A
Friday	Independent Study	15:30	17:00	 - 	CS442 - E-Commerce	Section B
Monday	Lecture	08:00	09:30	Nutor Hall 216	CS456 - Algorithm Design and Analysis	Section A
Tuesday	Lecture	08:00	09:30	Nutor Hall 216	CS456 - Algorithm Design and Analysis	Section A
Friday	Lab	10:20	11:50	Nutor Hall 216	CS456 - Algorithm Design and Analysis	Section A
Monday	Lecture	09:45	11:15	Nutor Hall 216	CS456 - Algorithm Design and Analysis	Section B
Tuesday	Lecture	09:45	11:15	Nutor Hall 216	CS456 - Algorithm Design and Analysis	Section B
Friday	Lab	08:30	10:00	Nutor Hall 216	CS456 - Algorithm Design and Analysis	Section B
Monday	Lab	15:00	16:30	Fab Lab 203	CS458 - Internet of Things	Section A
Tuesday	Lecture	11:30	13:00	Fab Lab 203	CS458 - Internet of Things	Section A
Thursday	Lecture	11:30	13:00	Fab Lab 203	CS458 - Internet of Things	Section A
Tuesday	Lecture	15:00	16:30	Jackson Lab 221	CS459 - Natural Language Processing	Section A
Thursday	Lecture	15:00	16:30	Jackson Lab 221	CS459 - Natural Language Processing	Section A
Friday	Lab	13:55	15:25	King Eng. Lab 102	CS459 - Natural Language Processing	Section A
Tuesday	Lecture	11:30	13:00	Jackson Lab 221	CS463 - Computer Vision	Section A
Wednesday	Lab	08:00	09:30	King Eng. Lab 102	CS463 - Computer Vision	Section A
Thursday	Lecture	11:30	13:00	Jackson Lab 221	CS463 - Computer Vision	Section A
Monday	For Grading	18:00	19:30	OT	CS491 - Undergraduate Thesis I (CS)	Section A
Tuesday	Lecture	09:45	11:15	Bio Lab	ECON 401 - Advanced Microeconomic Theory	Section A
Thursday	Lecture	09:45	11:15	Bio Lab	ECON 401 - Advanced Microeconomic Theory	Section A
Friday	Discussion	13:55	14:55	Norton-Motulsky 207B	ECON 401 - Advanced Microeconomic Theory	Section A
Tuesday	Lecture	15:00	16:30	Bio Lab	ECON 422 - Econometrics II	Section A
Wednesday	Lecture	15:00	16:30	Bio Lab	ECON 422 - Econometrics II	Section A
Friday	Discussion	12:15	13:45	Bio Lab	ECON 422 - Econometrics II	Section A
Monday	Discussion	13:45	14:45	EE lab	ECON 454 - Africa and the Oil Industry	Section A
Tuesday	Lecture	11:30	13:00	Bio Lab	ECON 454 - Africa and the Oil Industry	Section A
Thursday	Lecture	11:30	13:00	Bio Lab	ECON 454 - Africa and the Oil Industry	Section A
Monday	Lecture	08:00	09:30	Nutor Hall 100	ECON100 - Principles of Economics	Section A
Wednesday	Lecture	08:00	09:30	Nutor Hall 100	ECON100 - Principles of Economics	Section A
Friday	Discussion	09:10	10:10	Apt Hall 217	ECON100 - Principles of Economics	Section A
Monday	Lecture	09:45	11:15	Nutor Hall 100	ECON100 - Principles of Economics	Section B
Wednesday	Lecture	09:45	11:15	Nutor Hall 100	ECON100 - Principles of Economics	Section B
Friday	Discussion	08:00	09:00	Apt Hall 217	ECON100 - Principles of Economics	Section B
Tuesday	Lecture	13:15	14:45	Nutor Hall 216	ECON100 - Principles of Economics	Section C
Thursday	Lecture	13:15	14:45	Nutor Hall 216	ECON100 - Principles of Economics	Section C
Friday	Period	09:10	10:10	Databank Foundation Hall 218	ECON100 - Principles of Economics	Section C
Tuesday	Lecture	15:00	16:30	Nutor Hall 216	ECON100 - Principles of Economics	Section D
Thursday	Lecture	15:00	16:30	Nutor Hall 216	ECON100 - Principles of Economics	Section D
Friday	Discussion	08:00	09:00	Databank Foundation Hall 218	ECON100 - Principles of Economics	Section D
Monday	Lecture	08:00	09:30	Apt Hall 217	ECON201 - Principles of Microeconomics	Section A
Wednesday	Lecture	08:00	09:30	Apt Hall 217	ECON201 - Principles of Microeconomics	Section A
Friday	Discussion	13:55	14:55	Nutor Hall 115	ECON201 - Principles of Microeconomics	Section A
Monday	Lecture	11:30	13:00	Nutor Hall 216	ECON201 - Principles of Microeconomics	Section B
Wednesday	Lecture	11:30	13:00	Nutor Hall 216	ECON201 - Principles of Microeconomics	Section B
Friday	Discussion	12:15	13:15	Nutor Hall 216	ECON201 - Principles of Microeconomics	Section B
Friday	Independent Study	15:30	17:00	 - 	ECON202 - Principles of Macroeconomics	Section A
Monday	Lecture	11:30	13:00	Apt Hall 217	ECON231 - Mathematics for Economists	Section A
Wednesday	Lecture	11:30	13:00	Apt Hall 217	ECON231 - Mathematics for Economists	Section A
Thursday	Discussion	08:30	09:30	EE lab	ECON231 - Mathematics for Economists	Section A
Monday	Lecture	15:00	16:30	Jackson Hall 115	ECON301 - Intermediate Microeconomic Theory I	Section A
Wednesday	Lecture	15:00	16:30	Jackson Hall 115	ECON301 - Intermediate Microeconomic Theory I	Section A
Thursday	Discussion	12:00	13:00	Norton-Motulsky 207A	ECON301 - Intermediate Microeconomic Theory I	Section A
Monday	Lecture	09:45	11:15	Apt Hall 217	ECON303 - Intermediate Macroeconomic Theory I	Section A
Wednesday	Lecture	09:45	11:15	Apt Hall 217	ECON303 - Intermediate Macroeconomic Theory I	Section A
Friday	Discussion	10:20	11:20	Bio Lab	ECON303 - Intermediate Macroeconomic Theory I	Section A
Monday	Lecture	11:30	13:00	King Eng. Lab 102	ECON451 - Development Economics	Section A
Wednesday	Lecture	11:30	13:00	King Eng. Lab 102	ECON451 - Development Economics	Section A
Friday	Discussion	13:55	14:55	Bio Lab	ECON451 - Development Economics	Section A
Monday	Seminar	09:45	11:15	Bio Lab	ECON491 - Undergraduate Thesis I (ECON)	Section A
Wednesday	Seminar	13:15	14:45	Bio Lab	ECON491 - Undergraduate Thesis I (ECON)	Section A
Friday	Independent Study	15:30	17:00	 - 	EE222 - Circuits and Electronics	Section A
Monday	Lab	08:00	10:00	King Eng. Lab 102	EE320 - Signals & Systems	Section A
Wednesday	Lecture	08:00	09:30	Fab Lab 203	EE320 - Signals & Systems	Section A
Friday	Lecture	13:55	15:25	Fab Lab 203	EE320 - Signals & Systems	Section A
Monday	Lab	15:00	17:00	EE lab	EE341 - AC Electrical Machines	Section A
Wednesday	Lecture	09:45	11:15	EE lab	EE341 - AC Electrical Machines	Section A
Friday	Lecture	12:15	13:45	EE lab	EE341 - AC Electrical Machines	Section A
Monday	Lab	15:00	17:00	King Eng. Lab 102	EE421 - Digital and Analog Signal Processing in Telecommunications	Section A
Wednesday	Lecture	09:45	11:15	Fab Lab 303	EE421 - Digital and Analog Signal Processing in Telecommunications	Section A
Friday	Lecture	10:20	11:50	Fab Lab 303	EE421 - Digital and Analog Signal Processing in Telecommunications	Section A
Monday	Lab	08:00	10:00	EE lab	EE451 - Power Engineering	Section A
Wednesday	Lecture	13:15	14:45	EE lab	EE451 - Power Engineering	Section A
Friday	Lecture	13:55	15:25	EE lab	EE451 - Power Engineering	Section A
Monday	Lab	15:00	17:00	Norton-Motulsky 207A	EE453 - Power Systems Analysis	Section A
Wednesday	Lecture	08:00	09:30	EE lab	EE453 - Power Systems Analysis	Section A
Friday	Lecture	10:20	11:50	EE lab	EE453 - Power Systems Analysis	Section A
Tuesday	Lecture	15:00	16:30	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section A
Wednesday	Discussion	13:50	14:50	Nutor Hall 115	ENGL112 - Written and Oral Communication	Section A
Thursday	Lecture	15:00	16:30	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section A
Tuesday	Lecture	11:30	13:00	Apt Hall 216	ENGL112 - Written and Oral Communication	Section B
Wednesday	Discussion	15:00	16:00	Nutor Hall 115	ENGL112 - Written and Oral Communication	Section B
Thursday	Lecture	11:30	13:00	Apt Hall 216	ENGL112 - Written and Oral Communication	Section B
Tuesday	Lecture	11:30	13:00	Jackson Lab 222	ENGL112 - Written and Oral Communication	Section E
Wednesday	Discussion	15:00	16:00	EE lab	ENGL112 - Written and Oral Communication	Section E
Thursday	Lecture	11:30	13:00	Jackson Lab 222	ENGL112 - Written and Oral Communication	Section E
Tuesday	Lecture	15:00	16:30	Apt Hall 217	ENGL112 - Written and Oral Communication	Section D
Wednesday	Discussion	15:00	16:00	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section D
Thursday	Lecture	15:00	16:30	Apt Hall 217	ENGL112 - Written and Oral Communication	Section D
Tuesday	Lecture	13:15	14:45	Apt Hall 217	ENGL112 - Written and Oral Communication	Section C
Wednesday	Discussion	13:50	14:50	Apt Hall 217	ENGL112 - Written and Oral Communication	Section C
Thursday	Lecture	13:15	14:45	Apt Hall 217	ENGL112 - Written and Oral Communication	Section C
Tuesday	Lecture	15:00	16:30	Norton-Motulsky 207A	ENGL112 - Written and Oral Communication	Section G
Wednesday	Discussion	15:00	16:00	Apt Hall 217	ENGL112 - Written and Oral Communication	Section G
Thursday	Lecture	15:00	16:30	Norton-Motulsky 207A	ENGL112 - Written and Oral Communication	Section G
Tuesday	Lecture	13:15	14:45	Norton-Motulsky 207A	ENGL112 - Written and Oral Communication	Section F
Wednesday	Discussion	16:40	17:40	King Eng. Lab 102	ENGL112 - Written and Oral Communication	Section F
Thursday	Lecture	13:15	14:45	Norton-Motulsky 207A	ENGL112 - Written and Oral Communication	Section F
Monday	Lab	12:45	14:45	Fab Lab 303	ENGR112 - Introduction to Engineering	Section A
Wednesday	Lecture	11:30	13:00	Fab Lab 203	ENGR112 - Introduction to Engineering	Section A
Thursday	Lecture	09:45	11:15	Fab Lab 203	ENGR112 - Introduction to Engineering	Section A
Wednesday	Lecture	13:15	14:45	Fab Lab 303	ENGR212 - Instrumentation for Engineering	Section A
Friday	Lab	08:00	10:00	Fab Lab 203	ENGR212-LAB - Instrumentation for Engineering - LAB	Section A
Friday	Lab	10:10	12:10	Fab Lab 203	ENGR212-LAB - Instrumentation for Engineering - LAB	Section B
Monday	Lab	10:10	12:10	Fab Lab 303	ENGR311 - System Dynamics	Section A
Tuesday	Lecture	09:45	11:15	Fab Lab 303	ENGR311 - System Dynamics	Section A
Thursday	Lecture	09:45	11:15	Fab Lab 303	ENGR311 - System Dynamics	Section A
Wednesday	Seminar	15:00	17:00	Fab Lab 303	ENGR401-SEM - Engineering Capstone Seminar	Section A
Monday	Lab	12:45	14:45	Bio Lab	ENGR412 - Synthetic Biological Engineering	Section A
Wednesday	Lecture	11:30	13:00	Bio Lab	ENGR412 - Synthetic Biological Engineering	Section A
Thursday	Lecture	13:15	14:45	Bio Lab	ENGR412 - Synthetic Biological Engineering	Section A
Tuesday	Lecture	11:30	13:00	ME Lab	ENGR442 - Mechatronics	Section A
Wednesday	Lab	09:30	11:30	ME Lab	ENGR442 - Mechatronics	Section A
Thursday	Lab	11:30	13:00	ME Lab	ENGR442 - Mechatronics	Section A
Tuesday	Lecture	16:45	18:15	Jackson Hall 115	FRENC111 - Introductory French I	Section A
Thursday	Lecture	16:45	18:15	Jackson Hall 115	FRENC111 - Introductory French I	Section A
Tuesday	Lecture	13:15	14:45	Multipurpose Conference Room	FRENC122 - Professional French I	Section A
Thursday	Lecture	13:15	14:45	Multipurpose Conference Room	FRENC122 - Professional French I	Section A
Tuesday	Lecture	13:15	14:45	ME Lab	FRENC315 - Francophone Literature and Film	Section A
Thursday	Lecture	13:15	14:45	EE lab	FRENC315 - Francophone Literature and Film	Section A
Friday	For grading only (not attendance)	15:30	17:00	Radichel MPR	ICS510 - Foundations of Intelligent Systems Seminar	Section A
Monday	Seminar	08:00	09:30	Radichel MPR	ICS521 - Leadership & Ethics Seminar	Section A
Tuesday	Lab	13:30	16:30	Radichel MPR	ICS530 - Software Engineering Essentials	Section A
Thursday	Lecture	15:00	16:30	Radichel MPR	ICS530 - Software Engineering Essentials	Section A
Tuesday	Lecture	09:45	11:15	King Eng. Lab 102	ICS534 - Cloud Computing	Section A
Thursday	Lab	09:45	12:45	King Eng. Lab 102	ICS534 - Cloud Computing	Section A
Monday	Lecture	09:45	11:15	Radichel MPR	ICS552 - Machine Learning and Data Science	Section A
Wednesday	Lab	08:15	11:15	Radichel MPR	ICS552 - Machine Learning and Data Science	Section A
Monday	Lab	13:30	16:30	Radichel MPR	ICS553 - Deep Learning	Section A
Friday	Lecture	12:15	13:45	Radichel MPR	ICS553 - Deep Learning	Section A
Thursday	Lecture	08:00	09:30	Radichel MPR	ICS570 - Cybersecurity Essentials	Section A
Friday	Lab	08:00	11:00	Radichel MPR	ICS570 - Cybersecurity Essentials	Section A
Monday	Lecture	13:15	14:45	Jackson Lab 221	IS351 - Systems Analysis and Design	Section A
Wednesday	Lecture	13:15	14:45	Jackson Lab 221	IS351 - Systems Analysis and Design	Section A
Thursday	Lab	08:00	09:30	Jackson Lab 221	IS351 - Systems Analysis and Design	Section A
Tuesday	Lecture	15:00	16:30	Apt Hall 216	IS451 - Information and Systems Security	Section A
Thursday	Lecture	15:00	16:30	Apt Hall 216	IS451 - Information and Systems Security	Section A
Friday	Lab	13:55	15:25	Nutor Hall 216	IS451 - Information and Systems Security	Section A
Tuesday	Lecture	09:45	11:15	Jackson Hall 115	LLB213 - Constitutional Law I	Section A
Thursday	Lecture	09:45	11:15	Jackson Hall 115	LLB213 - Constitutional Law I	Section A
Friday	Discussion	08:00	09:00	EE lab	LLB213 - Constitutional Law I	Section A
Wednesday	Lecture	11:30	13:00	Radichel MPR	LLB215 - Contract Law I	Section A
Thursday	Lecture	08:00	09:30	Jackson Hall 115	LLB215 - Contract Law I	Section A
Monday	Lecture	09:45	11:15	Jackson Lab 222	LLB217 - Torts	Section A
Wednesday	Lecture	09:45	11:15	Jackson Lab 222	LLB217 - Torts	Section A
Friday	Discussion	13:55	14:55	Jackson Lab 222	LLB217 - Torts	Section A
Tuesday	Lecture	08:00	09:30	Jackson Hall 115	LLB221 - Statistics for Social Science	Section A
Thursday	Lecture	15:00	16:30	EE lab	LLB221 - Statistics for Social Science	Section A
Friday	Discussion	09:10	10:10	King Eng. Lab 102	LLB221 - Statistics for Social Science	Section A
Tuesday	Lecture	13:15	14:45	Jackson Lab 222	LLB255 - Economic Analysis for Public Policy	Section A
Thursday	Lecture	13:15	14:45	Jackson Lab 222	LLB255 - Economic Analysis for Public Policy	Section A
Friday	Discussion	08:00	09:00	Jackson Lab 222	LLB255 - Economic Analysis for Public Policy	Section A
Tuesday	Lecture	09:45	11:15	Jackson Lab 222	LLB321 - Criminal Law I	Section A
Wednesday	Lecture	08:00	09:30	Multipurpose Conference Room	LLB321 - Criminal Law I	Section A
Friday	Discussion	12:30	13:30	Jackson Lab 222	LLB321 - Criminal Law I	Section A
Monday	Lecture	13:15	14:45	Jackson Lab 222	LLB323 - Immovable Property Law I	Section A
Wednesday	Lecture	13:15	14:45	Jackson Lab 222	LLB323 - Immovable Property Law I	Section A
Friday	Lecture	09:20	11:20	Jackson Lab 222	LLB325 - Public International Law	Section A
Tuesday	Lecture	08:00	09:30	Jackson Lab 222	LLB351 - Designing Public Policy	Section A
Thursday	Lecture	08:00	09:30	Jackson Lab 222	LLB351 - Designing Public Policy	Section A
Monday	Lecture	08:00	09:30	Jackson Hall 116	MATH101 - College Algebra	Section A
Tuesday	Lecture	08:00	09:30	Jackson Hall 116	MATH101 - College Algebra	Section A
Wednesday	Lecture	08:00	09:30	Jackson Hall 116	MATH101 - College Algebra	Section A
Friday	Discussion	10:20	11:50	Norton-Motulsky 207A	MATH101 - College Algebra	Section A
Monday	Lecture	09:45	11:15	Norton-Motulsky 207A	MATH121 - Pre-Calculus I	Section A
Tuesday	Lecture	09:45	11:15	Radichel MPR	MATH121 - Pre-Calculus I	Section A
Wednesday	Lecture	09:45	11:15	Norton-Motulsky 207A	MATH121 - Pre-Calculus I	Section A
Friday	Discussion	12:15	13:45	Norton-Motulsky 207A	MATH121 - Pre-Calculus I	Section A
Monday	Lecture	11:30	13:00	Norton-Motulsky 207A	MATH121 - Pre-Calculus I	Section B
Tuesday	Lecture	11:30	13:00	Norton-Motulsky 207A	MATH121 - Pre-Calculus I	Section B
Wednesday	Lecture	11:30	13:00	Norton-Motulsky 207A	MATH121 - Pre-Calculus I	Section B
Friday	Discussion	13:55	15:25	Norton-Motulsky 207A	MATH121 - Pre-Calculus I	Section B
Monday	Lecture	08:00	09:30	Norton-Motulsky 207A	MATH122 - Pre-Calculus II	Section A
Tuesday	Lecture	08:00	09:30	King Eng. Lab 102	MATH122 - Pre-Calculus II	Section A
Wednesday	Lecture	08:00	09:30	Norton-Motulsky 207A	MATH122 - Pre-Calculus II	Section A
Friday	Discussion	12:15	13:45	King Eng. Lab 102	MATH122 - Pre-Calculus II	Section A
Monday	Lecture	09:45	11:15	Jackson Hall 116	MATH141 - Calculus I	Section A
Tuesday	Lecture	09:45	11:15	Jackson Hall 116	MATH141 - Calculus I	Section A
Wednesday	Lecture	09:45	11:15	Jackson Hall 116	MATH141 - Calculus I	Section A
Friday	Discussion	12:15	13:45	Jackson Hall 116	MATH141 - Calculus I	Section A
Monday	Lecture	11:30	13:00	Jackson Hall 116	MATH141 - Calculus I	Section B
Tuesday	Lecture	11:30	13:00	Jackson Hall 116	MATH141 - Calculus I	Section B
Wednesday	Lecture	11:30	13:00	Jackson Hall 116	MATH141 - Calculus I	Section B
Friday	Discussion	13:55	15:25	Jackson Hall 116	MATH141 - Calculus I	Section B
Tuesday	Lecture	13:15	14:45	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section A
Thursday	Lecture	13:15	14:45	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section A
Friday	Discussion	12:15	13:45	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section A
Tuesday	Lecture	15:00	16:30	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section B
Thursday	Lecture	15:00	16:30	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section B
Friday	Discussion	13:55	15:25	Fab Lab 303	MATH152 - Statistics for Engineering and Economics	Section B
Monday	Lecture	08:00	09:30	Fab Lab 203	MATH161 - Engineering Calculus	Section A
Wednesday	Lecture	09:45	11:15	Fab Lab 203	MATH161 - Engineering Calculus	Section A
Friday	Lecture	12:15	13:45	Fab Lab 203	MATH161 - Engineering Calculus	Section A
Monday	Lecture	09:45	11:15	Multipurpose Conference Room	MATH211 - Multivariable Calculus and Linear Algebra	Section A
Wednesday	Lecture	13:15	14:45	Multipurpose Conference Room	MATH211 - Multivariable Calculus and Linear Algebra	Section A
Friday	Discussion	09:45	11:15	Multipurpose Conference Room	MATH211 - Multivariable Calculus and Linear Algebra	Section A
Monday	Lecture	13:15	14:45	Databank Foundation Hall 218	MATH221 - Statistics	Section A
Tuesday	Lecture	08:00	09:30	Databank Foundation Hall 218	MATH221 - Statistics	Section A
Thursday	Discussion	08:00	09:30	Databank Foundation Hall 218	MATH221 - Statistics	Section A
Monday	Lecture	15:00	16:30	Databank Foundation Hall 218	MATH221 - Statistics	Section B
Tuesday	Lecture	09:45	11:15	Databank Foundation Hall 218	MATH221 - Statistics	Section B
Thursday	Discussion	09:45	11:15	Databank Foundation Hall 218	MATH221 - Statistics	Section B
Monday	Lecture	15:00	16:30	Jackson Hall 116	MATH221 - Statistics	Section E
Tuesday	Lecture	15:00	16:30	Databank Foundation Hall 218	MATH221 - Statistics	Section E
Thursday	Discussion	15:00	16:30	Databank Foundation Hall 218	MATH221 - Statistics	Section E
Monday	Lecture	13:15	14:45	Jackson Hall 116	MATH221 - Statistics	Section D
Tuesday	Lecture	13:15	14:45	Databank Foundation Hall 218	MATH221 - Statistics	Section D
Thursday	Discussion	13:15	14:45	Databank Foundation Hall 218	MATH221 - Statistics	Section D
Monday	Lecture	15:00	16:30	Nutor Hall 115	MATH221 - Statistics	Section C
Tuesday	Lecture	11:30	13:00	Databank Foundation Hall 218	MATH221 - Statistics	Section C
Thursday	Discussion	11:30	13:00	Databank Foundation Hall 218	MATH221 - Statistics	Section C
Sunday	Lecture	09:00	13:00	Radichel MPR	MBA511 - Financial Reporting and Control	Section A
Friday	Lecture	17:30	21:30	Radichel MPR	MBA511 - Financial Reporting and Control	Section A
Saturday	Lecture	09:00	18:00	Radichel MPR	MBA511 - Financial Reporting and Control	Section A
Sunday	Lecture	09:00	13:00	Radichel MPR	MBA541 - Marketing Management	Section A
Friday	Lecture	17:30	21:30	Radichel MPR	MBA541 - Marketing Management	Section A
Saturday	Lecture	09:00	18:00	Radichel MPR	MBA541 - Marketing Management	Section A
Sunday	Lecture	09:00	13:00	Radichel MPR	MBA551 - Managerial Economics	Section A
Friday	Lecture	17:30	21:30	Radichel MPR	MBA551 - Managerial Economics	Section A
Saturday	Lecture	09:00	18:00	Radichel MPR	MBA551 - Managerial Economics	Section A
Sunday	Lecture	09:00	13:00	Radichel MPR	MBA561 - Process Innovation and Technology	Section A
Friday	Lecture	17:30	21:30	Radichel MPR	MBA561 - Process Innovation and Technology	Section A
Saturday	Lecture	09:00	18:00	Radichel MPR	MBA561 - Process Innovation and Technology	Section A
Sunday	Lecture	09:00	13:00	Radichel MPR	MBA571 - Leadership, Ethics & A Good Society	Section A
Friday	Lecture	17:30	21:30	Radichel MPR	MBA571 - Leadership, Ethics & A Good Society	Section A
Saturday	Lecture	09:00	18:00	Radichel MPR	MBA571 - Leadership, Ethics & A Good Society	Section A
Monday	Lab	15:00	17:00	Fab Lab 303	ME212 - Thermodynamics	Section A
Wednesday	Lecture	08:00	09:30	Fab Lab 303	ME212 - Thermodynamics	Section A
Friday	Lecture	08:00	09:30	Fab Lab 303	ME212 - Thermodynamics	Section A
Monday	Lecture	13:15	14:45	Fab Lab 203	ME311 - Mechanics of Materials	Section A
Wednesday	Lab	15:00	17:00	Fab Lab 203	ME311 - Mechanics of Materials	Section A
Friday	Lecture	13:55	15:25	Science Lab	ME311 - Mechanics of Materials	Section A
Monday	Lab	15:00	17:00	Science Lab	ME401 - Mechanics of Machines & Engineering Vibration	Section A
Wednesday	Lecture	13:15	14:45	Science Lab	ME401 - Mechanics of Machines & Engineering Vibration	Section A
Friday	Lecture	10:20	11:50	Science Lab	ME401 - Mechanics of Machines & Engineering Vibration	Section A
Monday	Lab	08:00	10:00	ME Lab	ME422 - Heat Transfer	Section A
Tuesday	Lecture	08:00	09:30	ME Lab	ME422 - Heat Transfer	Section A
Thursday	Lecture	08:00	09:30	ME Lab	ME422 - Heat Transfer	Section A
Monday	Lab	08:00	10:00	Fab Lab 303	ME442 - Computer Aided Design and Manufacturing	Section A
Tuesday	Lecture	08:00	09:30	Fab Lab 303	ME442 - Computer Aided Design and Manufacturing	Section A
Thursday	Lecture	08:00	09:30	Fab Lab 303	ME442 - Computer Aided Design and Manufacturing	Section A
Monday	Lab	10:10	12:10	ME Lab	ME444 - Advanced Mechanical Machine Design	Section A
Tuesday	Lecture	09:45	11:15	ME Lab	ME444 - Advanced Mechanical Machine Design	Section A
Thursday	Lecture	09:45	11:15	ME Lab	ME444 - Advanced Mechanical Machine Design	Section A
Monday	Lecture	13:15	14:45	Norton-Motulsky 207B	POLS234 - Comparative Politics	Section A
Wednesday	Lecture	13:15	14:45	Norton-Motulsky 207B	POLS234 - Comparative Politics	Section A
Friday	Discussion	08:00	09:00	Jackson Hall 115	POLS234 - Comparative Politics	Section A
Tuesday	Lecture	11:30	13:00	Radichel MPR	POLS237 - African Trade and Regional Integration	Section A
Thursday	Lecture	11:30	13:00	Radichel MPR	POLS237 - African Trade and Regional Integration	Section A
Friday	Discussion	08:00	09:00	Jackson Lab 221	POLS237 - African Trade and Regional Integration	Section A
Monday	Lecture	15:00	16:30	Norton-Motulsky 207B	POLS332 - Governance in Africa	Section A
Wednesday	Lecture	15:00	16:30	Norton-Motulsky 207B	POLS332 - Governance in Africa	Section A
Friday	Discussion	09:10	10:10	Jackson Hall 115	POLS332 - Governance in Africa	Section A
Monday	Lab	10:10	12:10	Science Lab	SC113 - Physics: Electromagnetism	Section A
Wednesday	Lecture	09:45	11:15	Science Lab	SC113 - Physics: Electromagnetism	Section A
Thursday	Lecture	09:45	11:15	Science Lab	SC113 - Physics: Electromagnetism	Section A
Monday	Lab	12:45	14:45	Science Lab	SC113 - Physics: Electromagnetism	Section B
Wednesday	Lecture	11:30	13:00	Science Lab	SC113 - Physics: Electromagnetism	Section B
Thursday	Lecture	11:30	13:00	Science Lab	SC113 - Physics: Electromagnetism	Section B
Monday	Discussion	16:40	17:40	Fab Lab 203	SOAN111 - Leadership Seminar I: What Makes a Good Leader?	Section A
Tuesday	Seminar	09:45	11:15	Fab Lab 203	SOAN111 - Leadership Seminar I: What Makes a Good Leader?	Section A
Monday	Seminar	13:15	14:45	Apt Hall 217	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section A
Wednesday	Discussion	15:00	16:00	Databank Foundation Hall 218	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section A
Monday	Seminar	15:00	16:30	Apt Hall 217	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section B
Wednesday	Discussion	15:00	16:00	Science Lab	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section B
Tuesday	Seminar	09:45	11:15	Jackson Lab 221	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section E
Wednesday	Discussion	13:45	14:45	Databank Foundation Hall 218	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section E
Tuesday	Seminar	08:00	09:30	Jackson Lab 221	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section D
Wednesday	Discussion	16:40	17:40	Databank Foundation Hall 218	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section D
Monday	Seminar	13:15	14:45	Apt Hall 216	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section C
Wednesday	Discussion	16:40	17:40	Science Lab	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section C
Tuesday	Seminar	11:30	13:00	Science Lab	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section I
Wednesday	Discussion	12:00	13:00	Fab Lab 303	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section I
Tuesday	Seminar	15:00	16:30	EE lab	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section H
Wednesday	Discussion	13:45	14:45	Norton-Motulsky 207A	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section H
Tuesday	Discussion	13:15	14:15	EE lab	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section G
Wednesday	Seminar	15:00	16:30	Jackson Hall 116	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section G
Tuesday	Seminar	11:30	13:00	EE lab	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section F
Wednesday	Discussion	13:45	14:45	Fab Lab 203	SOAN211 - Leadership Seminar II: Rights, Ethics and Rule of Law	Section F
Tuesday	Lecture	15:00	16:30	Nutor Hall 115	SOAN225 - Ghanaian Popular Culture	Section A
Thursday	Lecture	15:00	16:30	Nutor Hall 115	SOAN225 - Ghanaian Popular Culture	Section A
Friday	Discussion	08:00	09:00	Science Lab	SOAN225 - Ghanaian Popular Culture	Section A
Tuesday	Lecture	13:15	14:45	Nutor Hall 115	SOAN238 - Introduction to Sociocultural Anthropology	Section A
Thursday	Lecture	13:15	14:45	Nutor Hall 115	SOAN238 - Introduction to Sociocultural Anthropology	Section A
Friday	Discussion	09:10	10:10	Science Lab	SOAN238 - Introduction to Sociocultural Anthropology	Section A
Monday	Discussion	16:45	17:45	Jackson Hall 116	SOAN240 - Neo-Traditional African Dance Forms	Section A
Tuesday	Lecture	11:30	13:00	King Eng. Lab 102	SOAN240 - Neo-Traditional African Dance Forms	Section A
Thursday	Lecture	11:30	13:00	Jackson Hall 116	SOAN240 - Neo-Traditional African Dance Forms	Section A
Tuesday	Lecture	13:15	14:45	Jackson Hall 116	SOAN301 - Introduction to Africana Studies: The Global Black Experience	Section A
Thursday	Lecture	13:15	14:45	Jackson Hall 116	SOAN301 - Introduction to Africana Studies: The Global Black Experience	Section A
Friday	Discussion	09:10	10:10	Norton-Motulsky 207A	SOAN301 - Introduction to Africana Studies: The Global Black Experience	Section A
Tuesday	Lecture	15:00	16:30	Jackson Hall 116	SOAN303 - Living Ghana’s History, Culture, and Politics	Section A
Thursday	Lecture	15:00	16:30	Jackson Hall 116	SOAN303 - Living Ghana’s History, Culture, and Politics	Section A
Friday	Discussion	08:00	09:00	Norton-Motulsky 207A	SOAN303 - Living Ghana’s History, Culture, and Politics	Section A
Thursday	Seminar	16:45	18:15	Apt Hall 216	SOAN328 - Creative and Research Internship	Section A
Thursday	Lecture	16:45	18:15	OT	SOAN329 - Creative and Research Internship II	Section A
Tuesday	Seminar	15:00	16:30	Jackson Lab 222	SOAN411 - Leadership Seminar IV: Leadership as Service	Section A
Thursday	Seminar	15:00	16:30	Jackson Lab 222	SOAN411 - Leadership Seminar IV: Leadership as Service	Section A
Tuesday	Seminar	11:30	13:00	Jackson Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section B
Thursday	Seminar	11:30	13:00	Jackson Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section B
Tuesday	Seminar	15:00	16:30	Science Lab	SOAN411 - Leadership Seminar IV: Leadership as Service	Section E
Thursday	Seminar	15:00	16:30	Science Lab	SOAN411 - Leadership Seminar IV: Leadership as Service	Section E
Tuesday	Seminar	15:00	16:30	Jackson Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section D
Thursday	Seminar	15:00	16:30	Jackson Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section D
Tuesday	Seminar	13:15	14:45	Jackson Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section C
Thursday	Seminar	13:15	14:45	Jackson Hall 115	SOAN411 - Leadership Seminar IV: Leadership as Service	Section C
Tuesday	Seminar	08:00	09:30	EE lab	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section A
Tuesday	Seminar	11:30	13:00	Fab Lab 303	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section A
Thursday	Seminar	11:30	13:00	Fab Lab 303	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section A
Tuesday	Seminar	15:00	16:30	Fab Lab 203	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section B
Thursday	Seminar	08:00	09:30	King Eng. Lab 102	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section B
Thursday	Seminar	15:00	16:30	Fab Lab 203	SOAN411_A - Leadership Seminar IV for Engineers: Leadership as Service	Section B